### ISSUE TITLE
add xpath support in owl

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#105]
maybe ?

The problem is the following: we have a component `A`, a component `B` which extends `A`.  `B` want to add a button somewhere in the template of `A`.  How does he do that? 

 **In classic Odoo**, we could write JS to add the button in the `start` method. 

**In Owl**, this can be done as well, with a `t-ref`, but then the widget `B` is responsible for managing (imperatively) all sub components, all handlers, ...

What would be useful is this:

```js
class B extends A {
  onButtonClick() {
    ...
  }
}
```

```xml
<t t-name="B" t-extend="A">
    <xpath expr="//some/selector" position="after">
        <button t-on-click="onButtonClick">Some Action</button>
    </xpath>
</t>
```

**Comment by LuisMalave2001** [comment]
I think this would be necessary for those cases when you are not using Odoo v14 or greater.

For example, I am trying to use some Owl functionalities in the point of sale of Odoo v13, when owl="1" isn't available.
In this scenario, adding some support to xpath and javascript extends would be very useful.
