### ISSUE TITLE
Translation on props not working 

### ISSUE THREAD

**Issue by ouail-nazim** [odoo/owl#1143]
is there any method to make translation work on the value of string props
i tried to use label="env._t('First name')" but it's not working 
and the only way to do it is with slot , but in my case , instead of using slots i want to translate the terms in the props binding

note : i'm using owl version   1.4.10

![1](https://user-images.githubusercontent.com/62262674/156536818-d58e774b-938f-4eb9-8f69-33f5f9d72ebd.png)

**Comment by ged-odoo** [comment]
it's weird. using `lavel="env._t("'First name')"` should work. Can you confirm that the `_t` function is properly defined in the environment?

**Comment by SimonGenin** [comment]
stalled
