### ISSUE TITLE
How to override a function of a Odoo service without patching the start() function

### ISSUE THREAD

**Issue by tiagosantosarxi** [odoo/owl#1162]
Just to give some context the idea is to re implement the function _triggerDownload from the ActionService (@web/webclient/actions/action_service)

I have read the documentation and have seen ways to patch components but not services.

Any help is appreciated.

As of right now the only way of doing this is patching the whole start function of the service. Although it works it does not seem to be the "best practice" to perform this override since I have to keep and manage all the code from the service in my re implementation.

**Comment by tiagosantosarxi** [comment]
Very helpful 🤦‍♂️

**Comment by ged-odoo** [comment]
He is right (your question is more about the odoo js code than owl). However, a little help is always nice.

In your case, services are not meant to be patched. The point is that we want to be able to change their implementations without breaking everyone code. The plan is however to make our services extremely configurable/generic/extensible.  Not making them easy to override(it can still be done, as you mentioned, by rewriting the service) is a short term price that we pay to get a long term benefit of safety+power.

So, in your case, could you tell us more about your need to override the triggerdownload function? Do you actually want to replace the code by some other code, or do you just need a way to execute code whenever this function is called?

**Comment by tiagosantosarxi** [comment]
Thanks for the quick response and for the help :)
Yes I got the idea that it is not easily reimplemented I just wasn't sure if I was missing something in order to safely patch a Service.

Just to clear up the purpose of overriding triggerdownload would be to call an external service(Printnode) for remote printing even in .SH environments without having to use IoT boxes, it is working atm but as you mentioned we will need to keep an eye on the regular updates to manage that piece of code.

Thanks!

**Comment by ged-odoo** [comment]
then, I think that the best solution would be to move the triggerDownload code from the action service to a `download` action in the action registry, and modifying the action service to use the download action from the registry. So, you can simply override the `download` action from the registry in your case, and it should work as expected. I'll try to get it done someday
