### ISSUE TITLE
props_validation: Is it really required to pass props with exact shape?

### ISSUE THREAD

**Issue by caburj** [odoo/owl#1189]
I think it's better if we allow passing an object that is structurally-compatible to the prop's shape. What I'm saying is that maybe, the following check might not be necessary.
https://github.com/odoo/owl/blob/a83731007af13a9d9d6585f403d1e6930cb33866/src/component/props_validation.ts#L143

**Comment by ged-odoo** [comment]
I am not sure, but I would lean toward saying that this check is mostly positive. Don't forget that when you describe the props received by your component, you can declare that it may receive additional props: 

```js
// either
SomeComponent.props = ['prop1', 'prop2', '*'];

// or
SomeComponent.props = {
  prop1: ...,
  prop2: ...,
  *: true
};
```
This means that `SomeComponent` accepts a structurally compatible prop object.  So, in many cases, this is not an issue.
However, when using a component authored by someone else (for example the framework team), and you want to pass some object as a `t-prop`, you then need to filter the unwanted keys.

So, the question is: do the benefits of the check outweigh this small issue? @sdegueldre @aab-odoo

**Comment by ged-odoo** [comment]
now that I think of it, if we think in terms of types and functions, it is indeed correct to call a function with an object that may have more keys than required.

**Comment by aab-odoo** [comment]
> now that I think of it, if we think in terms of types and functions, it is indeed correct to call a function with an object that may have more keys than required

In JS indeed, but is this a strength of the language, I don't think so.

**Comment by ged-odoo** [comment]
i just thought about a concrete example of the benefits provided by this check: if I have a component `A` with an optional props `something`, but then someone want to use my component like this: `<A somethinig="someValue"/>`, then without the check, the component `A` would accept the wrong prop, but will not use it. So, the code is wrong. However, with the additional check, we would know immediately that the prop was mispelled.

**Comment by caburj** [comment]
> i just thought about a concrete example of the benefits provided by this check: if I have a component `A` with an optional props `something`, but then someone want to use my component like this: `<A somethinig="someValue"/>`, then without the check, the component `A` would accept the wrong prop, but will not use it. So, the code is wrong. However, with the additional check, we would know immediately that the prop was mispelled.

I'm referring to a "propDef" with "shape" but I think the argument is valid and it's a very good one. It's hard to disagree.

How about allowing developers to switch this strict check off/on? Such that when it's off, owl don't crash, instead, it just issues a warning. This way, the developers have the ability to gradually type their component. Kinda like "gradual" typing in typescript which allows the code to compile even without full-typing, but and in owl's case, even without full-typing the props, the screen still renders. It's good for iteration.

**Comment by sdegueldre** [comment]
I think we should add support for "*": true in shape objects.

**Comment by ged-odoo** [comment]
https://github.com/odoo/owl/issues/1190
