### ISSUE TITLE
Is interacting with the component from the browser js console possible ?

### ISSUE THREAD

**Issue by selimb86** [odoo/owl#1239]
Hello,

I am in a case that I need to interact with a component from the browser js console. Is this possible ?

**Comment by LukeLonas** [comment]
Occasionally, for quickly debugging things, I've saved a reference to my component's instance on the `window` object which then lets me access it from the console easily. This can be helpful if I want to mutate the state, manually, for instance.

For a component that is only created once you may be able to get away with something as simple as the following:
```javascript
const {Component, useState, xml} = owl;

export class Counter extends Component {
    static template = xml`<button t-on-click="() => this.state.count++">[<t t-esc="state.count"/>]</button>`;

    setup() {
        window.counter = this; // <-- At this point your `this` is the instance of your component
        this.state = useState({count: 0})
    }
}
```

I can then do something like the following in my browser console and my component will automatically rerender:
```javascript
 counter.state.count = 10;
```

For cases where I have multiple instances of a component you could add them to an array on the `window` object and/or you could take a property that "names" each instance of the component such that they're all uniquely addressable.

**Comment by sdegueldre** [comment]
Currently there is no built-in way to interact with components from the console beyond storing a reference to the component on the window and manipulating the owl internals. We will soon publish owl devtools that will make this easier.
