### ISSUE TITLE
Odoo 14 translation Problem.

### ISSUE THREAD

**Issue by Laris15** [odoo/owl#1240]
Hello everyone, please i have an issue in odoo 14.
I have translated a module i created from English to French by exporting the fr.po file and translating each term in it. But i dont understand why when i change my Odoo language to French all my module is still in English. 

Please can anyone help me

_Originally posted by @Laris15 in https://github.com/odoo/owl/issues/926#issuecomment-1214962251_

**Comment by sdegueldre** [comment]
Please open an issue on the odoo repo, this has nothing to do with owl.
