### ISSUE TITLE
Rpc Query in Search Bar Component

### ISSUE THREAD

**Issue by polarity97** [odoo/owl#1242]
I have faced the following issue.
I am unable to perform rpc query in Search Bar Legacy. I tried by defining `const rpc = require('web.rpc');` in the head of my document but I keep getting rejected promise. 

If I try to use rpc service
```
const { useService } = require('@web/core/utils/hooks');
class ProductUiSearchBar extends SearchBar {
    setup() {
        this.rpc = useService("rpc");
    }
```

I get the following error: 
`Traceback (most recent call last):
  File "C:\odoo15\odoo\odoo\http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\odoo15\odoo\odoo\http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

I also tried to use orm service, but I got an error telling me that orm service is not available.
Is there any way to use rpc queries in Search Bar? Thanks in advance.

**Comment by polarity97** [comment]
Apparently I declared model in a wrong way in rpc method.

**Comment by flotho** [comment]
any chance to have a feedback and the final code you wrote ?

**Comment by sdegueldre** [comment]
The python error seems to indicate that the error is not on the JS side but that the controller was not declared correctly, or that there was a typo in the URL when trying to call it, it's just a normal 404 not found error.
