### ISSUE TITLE
Tutorial not up to date and reference not providing answers

### ISSUE THREAD

**Issue by Ronald1962** [odoo/owl#1243]
Hi, I try to follow the owl tutorial, which unfortunately is still based on previous owl versions.

I understand the store, step 10 of the tutorial, is no longer supported.

However step 9, that deals with handling deleting tasks is also no longer functional. My question is: how can an event on a child component (the Task) be handled on a parent component (containing the task list). 

This seems a rather elementary piece of functionality that I do not see an explanation for anywhere.

**Comment by Ronald1962** [comment]
It still stands that the tutorial is out of date, but step 9 is functional.

It was not quite clear that both the Task and the Root component need a deleteTask function, where the one in Task serves to callback the one on the Root component via the onDelete property.

**Comment by NL66278** [comment]
And no, tutorial not even out of date. Tested with owl 2.0 and is fully functional.
