### ISSUE TITLE
owl does not allow to add handlers on events with a dot in it

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#1247]
For example:
```xml
<div t-on-bs.popover="doSomething">asdf</div>
```
Instead, it will strip the `.popover` suffix and add the handler on the `bs` event.

Not a big deal, but this makes it annoying to interact with bootstrap events, for example.  Should we whitelist the list of suffixes that we remove? Or maybe have a way to namespace it? `t-on-bs_popover="doSomething"`

**Comment by sdegueldre** [comment]
(as a note, as event types can be arbitrary strings, there are many other types of events that just cannot be listened to as you can't write a valid attribute name containing the event type)

**Comment by sdegueldre** [comment]
We discussed this previously and decided to keep the current behaviour, it's always possible to add handlers for weird event types by hand in useEffect
