### ISSUE TITLE
t-call-context breaks with dev mode when called template tries to render component

### ISSUE THREAD

**Issue by LukeLonas** [odoo/owl#1261]
I've run into a case where I'd like to use `t-call-context` to abstract what my template knows about its caller. This template includes a component in its structure. Everything works fine without `dev: true` but with dev mode on I get the following:

![image](https://user-images.githubusercontent.com/16693361/192032256-2d7f3e72-9b03-4f80-9ed0-31547d3cc288.png)

I've created a simple project that highlights the issue. The files of interest in this project are as follows:
### templates.xml:
```xml
<templates>
    <main t-name="Root">
        <Counter/>
        <t t-call="counter.label" t-call-context="{label: 'A Label: '}"/>
    </main>

    <button t-name="Counter" t-on-click="() => this.state.count++">Increment [<t t-esc="state.count"/>]</button>

    <div t-name="counter.label">
        <t t-out="label"/>
        <Counter></Counter>
    </div>
</templates>
```

### app.js
```js
import {Root} from "./Root.js";

const {loadFile, mount} = owl;

(async function setup() {
    mount(Root, document.body, {
        templates: await loadFile("../templates.xml"),
        dev: true,
    });
})();
```

### Root.js
```js
import {Counter} from "./Counter.js";

const {Component} = owl;

export class Root extends Component {
    static template = "Root";
    static components = {Counter};
}
```

### Counter.js
```js
const {Component, useState} = owl;

export class Counter extends Component {
    static template = "Counter";

    setup() {
        this.state = useState({count: 0})
    }
}
```

## What I've tried:

- Adding `constructor` to t-call-context via `this.constructor`
  - This gets me past this error, but then I get errors about `n.__owl__`

**Comment by ged-odoo** [comment]
nice catch.  as a temporary workaround, you can add `constructor` and `__owl__` in the t-call-context:

```xml
        <t t-call="counter.label" t-call-context="{label: 'A Label: ', constructor, __owl__}"/>
```
but obviously, this should just be temporary, until you can get the fix
