### ISSUE TITLE
Please 🙏, make component lifecycle methods optional on version 2.0

### ISSUE THREAD

**Issue by pedrovagner** [odoo/owl#1264]
This is not an issue, it's a question (almost a complain).

I cannot express how happy I was to hear about the goals of the OWL project ([source](https://github.com/odoo/owl/blob/master/doc/miscellaneous/why_owl.md)):

> Odoo has another specific use out of class components: each method of a class provides an extension point for addons... using React or Vue would make it significantly harder to monkey patch components, because a lot of the state is hidden in their internals.

I cannot express how sad I'm right now to notice that from Owl 1.x to Owl 2.0 component lifecycle methods has been removed ([source](https://github.com/odoo/owl/blob/master/CHANGELOG.md#1-component-lifecycle-methods-are-removed)).

I think this is a bad decision, because "hooks" makes more difficult to change an existing component behavior from an external addon (Odoo's biggest feature / achievement / win). Even React don't removed component lifecycle completely (it keeps allowing class based components declaration).

Please, make component lifecycle methods optional on Owl 2.0!

I go beyond and ask you guys to make "hooks" deprecated and to emphasize "inheritance over composability" even if this means less faster and less efficient components. Let's face, "hooks" are an awkward feature, and be faster and efficient is not the most important think. If it was the case, Odoo should deprecate Python in favor of C++.

@ged-odoo only you can save this project 🙏

**Comment by pedrovagner** [comment]
This is another suggestion: Please, don't use the word "patch" when someone try to extend an existing component class. This is a bad name in the programming jargon. Consider another name, like register, extend, include, etc. By the way, "include" is the name used by the old widget component. This name is good.

**Comment by pedrovagner** [comment]
Another observation: Angular's component lifecycle are completely method based.

**Comment by ged-odoo** [comment]
Dear @pedrovagner Thank you for your well-explained issue. It deserves a more complete answer, but we are currently getting ready for odoo 16 and I don't have much time now. If I can, I'll get back to you later.  In the meantime, I just want to tell you that it is still possible to patch components lifecycle using hooks:

```js
patch(SomeComponent.prototype, 'mypatch', {
  setup() {
    this._super();
    onMounted(() => {
      // do something here
    });
  }
});

The only case where you are more limited is if you want to stop/customize the content of a hook defined in a component. Note that when we have a non trivial amount of logic, we often do this:
```js
class MyComponent extends Component {
  setup() {
    onMounted(() => this.doSomething());
  }
  doSomething() {...}
}
```
In that case, you can easily patch the `doSomething` method.  If the component is not written like that, we will definitely easily accept a PR to change it.

Sorry, I know that it is probably not what you want, and I would gladly discuss this more in depth, but I can't take more time for this discussion now. Hope it helps a little bit.

**Comment by ged-odoo** [comment]
Also, you may not feel like this, but know that I really take this issue seriously. Customizing code is indeed important.

**Comment by pedrovagner** [comment]
@ged-odoo thanks for your answer. I think there is no need to continue this discussion, it became quite clear how things will work from now on. It will be very sad to see someone putting a great amount of logic inside setup, but I can live with it.

I wish you luck with your Odoo 16 presentation.

**Comment by ged-odoo** [comment]
@pedrovagner 
it just occurred to me that it may still be possible to patch all lifecycle hooks, if one is ready to access owl internal representation. Something like this may work (warning: code is untested! this is only some pseudo code to show the point):
```js
import { patch } from "@web/core/utils/patch";

let id = 1;
const hookMap = {
  onWillStart: willStart,
  onWillUpdateProps: willUpdateProps,
  onMounted: mounted,
  onWillUnmount: willUnmount,
  onWillPatch: willPatch,
  onWillDestroy: willDestroy,
};

export function patchHooks(Comp, patches) {
  patch(Comp.prototype, `patch_hook_${id++}`, {
    setup() {
      this._super(); // we let parent setup first, so all hooks are registered
      const node = this.__owl__; // get reference to internal stuff

      // this does not work for onWillRender and onRendered. something else should be done
      for (let hook in hookMap) {
        if (hook in patches) {
            const internalHook = hookMap[hook];
            const cbs = node[internalHook];
            node[internalHook] = [() => {
                this._super = () => {
                  const proms = [];
                  for (let cb of cbs) {
                    const result = cb.call(this);
                    if (result instanceof Promise) {
                      proms.push(result);
                    }
                  }
                  return proms.length && Promise.all(proms) 
                };
                patches[hook].call(this);
            }];
        }
      }
    }
  }
};
```

Then it could be used like this:
```js
patchHooks(SomeComponent, {
  async onWillStart() {
    await this._super();
    // do something
  }
  onMounted() {
    this._super();
    // do something here
    // ...
  },
  onWillUnmount() {
    // do something here
    // ...
   this._super();
  },
});
```

**Comment by pedrovagner** [comment]
@ged-odoo thanks again for your feedback.

I'm currently developing components using OWL 1.0, so it will take sometime until I start working with OWL 2.0. When this happen, I will test your code and provide you some feedback. But I thing this will never happen, because I just take an overview on Odoo 16 codebase and realize there is a minimal amount of logic putting inside `setup`, that is, the code is well written (and I plan to do the same). Maybe there will never be a need to replace `setup` to "turn off" some hook, so it's not that different from an object oriented perspective (as I thought previously).

By the way, I watched your presentation about OWL 2.0 and I was amazed how `blockdom` is blazing fast! Congrats for your achievement 👏👏👏
