### ISSUE TITLE
Variablized component in foreach throws error: this.fiber is null

### ISSUE THREAD

**Issue by LukeLonas** [odoo/owl#1270]
# The Issue:
I've encountered an issue where outputting the result of a `t-set` that contains a component within a foreach loop **(that itterates more than once)** causes an exception. Specifically, the exception is:

![image](https://user-images.githubusercontent.com/16693361/192649832-8f81f136-97b2-4f93-9cc0-cd8322039785.png)

I've done a lot of testing with this and have been able to distill the issue down to a few simple cases that showcase the issue as shown below. It should be noted that I was able to reproduce the issue in beta-20, beta-21, and using the fix provided in PR #1268.

# Scenarios that reproduce the issue:

Notes:
- I realize that setting a variable and then immediately `t-out`ing it is fairly unrealistic, but it was a simple way to capture the issue. Setup 3 captures a more realistic scenario.
- The following scenarios all use the same `Counter` component:

#### Counter.js:
```javascript
const {Component, useState, xml} = owl;

export class Counter extends Component {
    static template = xml`<button t-on-click="() => this.state.count++">[<t t-esc="state.count"/>]</button>`;

    setup() {
        this.state = useState({count: 0})
    }
}
```

## Setup 1:
```xml
    <main t-name="Root">
        <t t-foreach="[1,2]" t-as="n" t-key="n">
            <t t-set="footer">
                <Counter/>
            </t>
            <t t-out="footer"/>
        </t>
    </main>
```

## Setup 2:
```xml
    <main t-name="Root">
        <t t-set="footer">
            <Counter/>
        </t>
        <t t-foreach="[1,2]" t-as="n" t-key="n">
            <t t-out="footer"/>
        </t>
    </main>
```

## Setup 3:
```xml
    <main t-name="Root">
        <t t-foreach="[1,2]" t-as="n" t-key="n">
            <t t-call="container">
                <h1>Hello World!</h1>
                <t t-set="footer">
                    <Counter/>
                </t>
            </t>
        </t>
    </main>

    <div t-name="container" class="container">
        <div class="content" t-out="0"/>
        <div class="footer" t-out="footer"/>
    </div>
```

**NOTE: All of these scenarios work if the foreach only itterates once. (e.g. `t-foreach="[1]"`)**

**Comment by ged-odoo** [comment]
thank you again for your bug report. I hope that you won't have the impression that Owl is riddled with bugs :/

Anyway, fix incoming, the issue was a missing `key` information in the content of the `t-out`.

**Comment by LukeLonas** [comment]
Sure thing, happy to help where I can.

Thank you for all your hard work creating and maintaining OWL. I've been really impressed with it!
