### ISSUE TITLE
json not available in global template scope

### ISSUE THREAD

**Issue by amh-mw** [odoo/owl#1273]
Various examples exist in the Odoo 15.0 codebase where an owl="0" template is able to reach certain symbols in the global scope, i.e. `json` and `request` in [discuss_public_templates.xml#L12-L17](https://github.com/odoo/odoo/blob/15.0/addons/mail/views/discuss_public_templates.xml#L12-L17)

```
<script>
    window.odoo = {
        __session_info__: <t t-out="json.dumps(session_info)"/>,
        csrf_token: "<t t-out="request.csrf_token(None)"/>",
        debug: "<t t-out="debug"/>",
    };
```

I believe these symbols correspond to those documented for the [View-based render() function](https://www.odoo.com/documentation/15.0/developer/reference/frontend/qweb.html#render).

Are these going away for good with owl="1"? I'm working on a small prototype that attempts to display help text for the current action in the available white space of the control panel. It fails with the error:

> Uncaught Promise > undefined is not an object (evaluating 'scope['json'].loads')

for this sample code:

```
<t t-set="current_action" t-value="window.sessionStorage.current_action"/>
<t t-if="current_action">
    <p t-esc="json.loads(current_action).get('help')" style="font-size: 18px;"/>
</t>
```

I'm just patching this piece inside the owl="1" [web.ControlPanel](https://github.com/odoo/odoo/blob/15.0/addons/web/static/src/search/control_panel/control_panel.xml#4) template for now.

**Comment by ged-odoo** [comment]
Hello @amh-mw 
First of all, there is a huge difference between the symbols that can be accessed in a view as you documented and owl templates: views are rendered by the server (so, they can access the `request` object and all available python symbols), while owl templates are rendered by the browser (so, they can access the rendering context, which is usually the component, and all available javascript symbols).

Note that you can access the window object, so you can use `window.odoo.debug` in an owl template.  If you want to manipulate json, you can use `window.JSON`. For example, `window.JSON.parse(something)`. Note that it is javascript, and not python, so you cannot use `.get` to access a key, but rather the usual js syntax `obj.help`
