### ISSUE TITLE
t-model should (?) be applied before t-on-input

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#1295]
Consider this code:

```xml
  <t t-name="Root">
    <input t-model="state.value" t-on-input="onInput"/>
  </t>
```
```js
class Root extends Component {
    static template = "Root"

    setup() {
        this.state = useState({ value: 'world'});
    }
    onInput(ev) {
        console.log(this.state.value, ev.target.value)
    }
}
```
writing in the input something will fire the onInput event first, and only then the t-model, so what you will see in the console is something like this: `world worldd`. I think that it is not totally intuitive, in my opinion the t-model should have precedence. Also, it makes some code more complicated: instead of reading the reflected value in the state, the code has to get it from the input.

**Comment by sdegueldre** [comment]
:+1:

**Comment by pga-odoo** [comment]
for similar cases i have used
``` javascript
onWillUpdateProps(nextProps => {
    this.onInput(nextProps);
});
```
BTW, I didn't need the event object.
