### ISSUE TITLE
Attribute values treat \ as escape

### ISSUE THREAD

**Issue by LukeLonas** [odoo/owl#1300]
Template attribute values use `\` character as escape. I don't know if this is expected behavior or not? I can imagine changing this could be a compatibility breaking change. It is also possible to work around by simply escaping the escape character. I just wanted to put it out there because it lead to unexpected behavior when I was creating a template.

Template:
```xml
<input type="text" pattern="^\S+$">
```

Output:
```html
<input type="text" pattern="^S+$">
```

**Comment by ged-odoo** [comment]
oh nice find. looks like a bug indeed :/
