### ISSUE TITLE
Support document as a target for useExternalListener

### ISSUE THREAD

**Issue by rrahir** [odoo/owl#1323]
Some events are dispatched on document directly, like [this](https://developer.mozilla.org/en-US/docs/Web/API/Document/selectionchange_event). The typing could support document as well?

**Comment by ged-odoo** [comment]
it's only a typing issue right? you just want this type:
```
  target: HTMLElement | typeof window | typeof document
```
right?

**Comment by rrahir** [comment]
yup :)

**Comment by sdegueldre** [comment]
It should probably just be `EventTarget`.
