### ISSUE TITLE
add optional name  to App

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#1342]
When mounting an app, it could be useful to add a name option, so the devtools could display them. This can be useful when there are many apps.

```js
const app = new App(MyComponent, {
  name: "my pretty application",
  props: {...},
  templates: "..."
});
app.mount(...)
```

**Comment by sdegueldre** [comment]
The devools could just default to the name of name component with the `App: ` prefix which would already help a lot (eg: `App: WebClient`)
