### ISSUE TITLE
anonymous function props always cause a rerender

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#1360]
It is quite common to have an anomymous function prop (for example, in a `t-foreach`):

```xml
  <t t-foreach="todos" t-as="todo" t-key="todo.id">
    <Todo todo="todo" onDelete="() => deleteTodo(todo.id)" />
</t>
```

However, then, the function prop will always be a different reference for each rendering, causing Owl to update the component. 

It completely makes sense from Owl perspective, but maybe we could do something to skip some renderings. Here are two possible ideas:
- find a way to detect anonymous functions (or maybe only `.bind` functions) when compiling expressions, and modify emitted code to reuse same function
- or maybe modify the props comparison code to consider different references of the same functions equal
- or maybe use the fact that we know at compile time which functions are anonymous, and simply skip them from the props comparison code. This last approach seems better, I think

Special care will need to be taken to make sure that captured values are correct, especially in a `t-foreach`. For example, currently, the above snippet is compiled into something like this: 

```js
      const v1 = ctx['deleteTodo'];
      const v2 = ctx['todo'];
      const props1 = {todo: ctx['todo'],onDelete: ()=>v1(v2.id)};
```

The `v1` and `v2` have to be captured, because the callback will be called later, and need to reflect the state of the current iteration in the for loop.

**Comment by ged-odoo** [comment]
Maybe it is not really possible. Not sure. An obvious problem is that it is not safe to skip component updates in some cases. Imagine some component that display the value returned by a function:
```xml
    <SomeComponent value="() => value"/> 
```

**Comment by sdegueldre** [comment]
Maybe we can provide a `.memo` or `.callback` suffix with special syntax to specify dependencies similar to react's useCallback? This way the end user has control over the memoization when they need it and we avoid having to do magic that risks breaking things.

**Comment by ged-odoo** [comment]
yes, i came to the same conclusion. I was thinking about using `.static` or `.noupdate`, but `.memo` sounds better

**Comment by ged-odoo** [comment]
also, not sure how to specify dependencies, but I think the case with no dependency is enough for now.

**Comment by sdegueldre** [comment]
We may want to think about the same problem being caused by slots, maybe there's an opportunity to solve both problems at once.

**Comment by ged-odoo** [comment]
true. note that I experimented with `t-memo` (fun fact: it is still present in code https://github.com/odoo/owl/blob/master/tests/compiler/t_foreach.test.ts#L238), but I kind of decided against talking about it. There is however a big difference: the `t-memo` directive applies to the node it is applied on, and here, we are talking about a specific prop for a component. But clearly, for slots, we could have something like this:
```xml
<ComponentA>
  <t t-set-slot="slot name" t-memo="[...]">
    some content
  </t>
</ComponentA>
```
It's still different, because we actually want to prevent the rendering of ComponentA. So, maybe what we should do is this instead:
```xml
<ComponentA  t-memo="[...]">
  <t t-set-slot="slot name">
    some content
  </t>
</ComponentA>
```

**Comment by ged-odoo** [comment]
Here is a WIP pr that implements the `.memo` suffix. Note that it is not really implemented as a memo, it simply ignores memoized props from the comparison algorithm, so maybe it should not be called memo. Or maybe it should, because it is a nice name... As a bonus (I think)¸ this let us simplify the `.bind` suffix. However, this implementation does not seem to be easily extensible to the case where we would potentially handle dependencies.

What do you think @sdegueldre ?

**Comment by ged-odoo** [comment]
better with the link https://github.com/odoo/owl/pull/1361

**Comment by sdegueldre** [comment]
Seems like a breaking change, bound functions are no longer referentially equal accross renders if another prop changes, and I think keeping referential equality can be desirable for reasons other than render optimization. What do you think of something like this? (not sure about slots using the same API, since you could want to memoize different slots differently)
```xml
<Component cbProp="() => capturedValue" t-memoized-props="{ cbProp: [capturedValue], slots: [someValue] }">
  <t t-esc="someValue"/>
</Component>
```

**Comment by ged-odoo** [comment]
I feel like the main benefit of `.bind` was to have the render optimization. In the rare (?) case where referential equality is desired, the component can just do `this.myMethod = this.myMethod.bind(this)` in its setup.

However, note that the change to `.bind` is not really necessary. It is done in a different commit, but we can just not do it if we want. I think that the implementation in PR 1361 is very simple, and the semantics feel good to me. I only have 2 minor issues:
- the word `memo` may be misleading. It is basically only memoized with respect to the props comparison step. If a component with a `memo` prop is updated, it will get the latest version anyway
- it is not clear how to extend the `memo` to values with a dependency list, or to slots

So, not sure how to proceed, but I prefer this solution to your `t-memoized-props` suggestion, because it feels more "natural".
