### ISSUE TITLE
Support element/key for object types during prop validation

### ISSUE THREAD

**Issue by sdegueldre** [odoo/owl#1394]
Sometimes, objects are used as a mapping, where the keys are arbitrary (or follow a certain format but are not known in advance), and the values should conform to a certain shape. In typescript, you can use:
```ts
type schema = {
  [key: string]: subSchema,
}
```

I propose the following syntax:
```js
const schema = {
  type: Object,
  // validates keys, generally would be omitted but you could
  // use a validate function here to enforce specific string format
  keys: subSchema, 
  values: otherSubSchema,
}
```

**Comment by sdegueldre** [comment]
Currently this can be implemented relatively easily using a custom validator and owl.validate:
```js
import { validate } from "@odoo/owl";
const schema = {
  type: Object,
  validate: (obj) => {
    for (const key in obj) {
      if (!validate(key, keySchema)) {
        return false;
      } else if (!validate(obj[key], valueSchema)) {
        return false;
      }
    }
    return true;
  },
}
```
But it seems like it should probably be supported directly in owl.

**Comment by ged-odoo** [comment]
sounds good (even though, unless I am missing something, the validation on keys will almost never be used (it only makes sense with a custom validation function, because the type is always string))
