### ISSUE TITLE
component doesn't re render when props are changed

### ISSUE THREAD

**Issue by nithin-gith** [odoo/owl#1458]
```xml
<t t-name="crm.graph_1" owl ="1">
        <t t-esc="state.value"/>
        <div class = "graph">
            <LineGraph data = "statistics" label = "'Customer Data'"/>
        </div>
</t>
```
LineGraph component is not being re rendered while statistics variable is changed as shown below

```js
setup() {
      this.statistics=useState({value:{}});
}

MonthlyView(){
        console.log("MONTHly");
        (async () => {
            this.statistics = await this.rpc("/web/dataset/custom",{});
            console.log(this.statistics);
        })();
    }
```

can someone find out what is the causing this behaviour and how to overcome this

**Comment by ged-odoo** [comment]
This is because you actually don't change the reactive value that you create in the setup function, you replace it, so in reality, the content of the initial variable didn't change. What you can do instead is to mutate the content of the variable instead:
```js
            // replace  this.statistics = await this.rpc("/web/dataset/custom",{}); by:
            const newData = await this.rpc("/web/dataset/custom",{});
            Object.assign(this.statistics, newData);
```
The difference is that by doing this, you now assign new value to the content of the statistics variable

**Comment by ged-odoo** [comment]
that is weird indeed then. Maybe the data received by your rpc is empty? If not, can you try to make a minimal example on the playground? https://odoo.github.io/owl/playground/

**Comment by ged-odoo** [comment]
Also, it is unclear if you mean to read data in `this.state` or `this.statistics`?

**Comment by nithin-gith** [comment]
i dont have any variable this.state. 
i only have this.statistics with useState hook like i mentioned in code

**Comment by caburj** [comment]
> yes, the `<t t-esc="state.value"/>` in the template was just for testing whether useState hook is working or not that was not the issue tho!
> 
> but the real issue i have is that does owl really re render child components when props of child component are updated??
> 
> by child component i mean <Component_1 /> - parent component <Component_2 /> - child component which is called inside component_1 does component_2 re render when props of component_2 is changed in the code of component_1

Yes, I think it should. Try the following example in the owl playground:

```js
import { Component, useState, mount, onRendered } from "@odoo/owl";

class Child extends Component {
    static template = "Child";
    setup() {
        this.nRenders = 0
        onRendered(() => {
            this.nRenders++;
        })
    }
}

class Parent extends Component {
    static components = { Child };
    static template = "Parent"
    setup() {
        this.state = useState({ name: 'World'});
        setInterval(() => {
            this.state.name = this.state.name === 'World' ? 'Universe' : 'World';
        }, 1000)
    }
    get strState() {
        return JSON.stringify(this.state, null, 2)
    }
}

mount(Parent, document.body, { templates: TEMPLATES, dev: true });
```

```xml
<templates>
  <div t-name="Child">
    <p>Child - number of renders: <t t-out="nRenders" /></p>
    <p>Child - received props: <t t-out="props.name" /></p>
  </div>

  <div t-name="Parent">
    <p>Parent - state:</p>
    <p><pre t-out="strState" /></p>
    <Child name="state.name"/>
  </div>
</templates>
```

The child component receives as props the `state.name` of the parent. The parent declares a setInterval that changes its `state.name` every second. The child is setup to show the number of its renders. If you run the above code, you'll see that the changing `parent.state.name` results to rerender of the child.
