### ISSUE TITLE
Unexpected value when doing a t-call with t-set and using the variable in a slot

### ISSUE THREAD

**Issue by BastienFafchamps** [odoo/owl#1492]
When we do a t-foreach and a t-set then make a t-call, the variable will no longer have the right value if it's used in a slot inside the t-call.

Exemple:
```xml
<t name="template-a">
    <t t-foreach="items" t-as="item" t-key="item.key">
        <t t-set="foo" t-value="item"/>
        <t t-call="template-b"/>
    </t>
</t>

<!-- This does not output the expected result -->
<t name="template-b">
    <Comp>
        <p t-out="foo.bar"></p>
    </Comp>
</t>
```

**Comment by sdegueldre** [comment]
[Other example of the weird behaviour](https://odoo.github.io/owl/playground/#eyJqcyI6ImltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50IH0gZnJvbSBcIkBvZG9vL293bFwiO1xuXG5jbGFzcyBBIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIkFcIjtcbn1cbmNsYXNzIFJvb3QgZXh0ZW5kcyBDb21wb25lbnQge1xuICAgIHN0YXRpYyBjb21wb25lbnRzID0geyBBIH07XG4gICAgc3RhdGljIHRlbXBsYXRlID0gXCJSb290XCI7XG59XG5tb3VudChSb290LCBkb2N1bWVudC5ib2R5LCB7IHRlbXBsYXRlczogVEVNUExBVEVTLCBkZXY6IHRydWUgfSk7XG4iLCJjc3MiOiIuZ3JlZXRlciB7XG4gICAgZm9udC1zaXplOiAyMHB4O1xuICAgIHdpZHRoOiAzMDBweDtcbiAgICBoZWlnaHQ6IDEwMHB4O1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogMTAwcHg7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2VlZWVlZTtcbiAgICB1c2VyLXNlbGVjdDogbm9uZTtcbn1cbiIsInhtbCI6Ijx0ZW1wbGF0ZXM+XG4gIDx0IHQtbmFtZT1cInN1YnRlbXBsYXRlXCI+XG4gICAgPEEgZ2V0VmFsPVwiKCkgPT4gdmFsXCIgdC1lc2M9XCJ2YWxcIi8+XG4gIDwvdD5cbiAgXG4gIDx0IHQtbmFtZT1cIkFcIj5cbiAgICA8dCB0LXNsb3Q9XCJkZWZhdWx0XCIvPlxuICAgIDx0IHQtZXNjPVwicHJvcHMuZ2V0VmFsKClcIi8+XG4gIDwvdD5cbiAgXG4gIDx0IHQtbmFtZT1cIlJvb3RcIj5cbiAgICA8dCB0LWZvcmVhY2g9XCJbMSwgMiwgM11cIiB0LWFzPVwidmFsXCIgdC1rZXk9XCJ2YWxcIj5cbiAgICAgIDx0IHQtY2FsbD1cInN1YnRlbXBsYXRlXCIvPlxuICAgICAgPGJyLz5cbiAgICAgIDxBIGdldFZhbD1cIigpID0+IHZhbFwiIHQtZXNjPVwidmFsXCIvPlxuICAgICAgPGJyLz5cbiAgICA8L3Q+XG4gIDwvdD5cbjwvdGVtcGxhdGVzPlxuIn0=)

**Comment by sdegueldre** [comment]
After discussion with @ged-odoo it's likely that a proper fix would require either breaking changes or large performance penalties, so we are tentatively deciding to simply live with the issue, one simple workaround for this specific problem is to capture the value by hand using a t-set at the top level of the t-call, as showcased in [this variant](https://odoo.github.io/owl/playground/#eyJqcyI6ImltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50IH0gZnJvbSBcIkBvZG9vL293bFwiO1xuXG5jbGFzcyBBIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIkFcIjtcbn1cbmNsYXNzIFJvb3QgZXh0ZW5kcyBDb21wb25lbnQge1xuICAgIHN0YXRpYyBjb21wb25lbnRzID0geyBBIH07XG4gICAgc3RhdGljIHRlbXBsYXRlID0gXCJSb290XCI7XG59XG5tb3VudChSb290LCBkb2N1bWVudC5ib2R5LCB7IHRlbXBsYXRlczogVEVNUExBVEVTLCBkZXY6IHRydWUgfSk7XG4iLCJjc3MiOiIuZ3JlZXRlciB7XG4gICAgZm9udC1zaXplOiAyMHB4O1xuICAgIHdpZHRoOiAzMDBweDtcbiAgICBoZWlnaHQ6IDEwMHB4O1xuICAgIG1hcmdpbjogNXB4O1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogMTAwcHg7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2VlZWVlZTtcbiAgICB1c2VyLXNlbGVjdDogbm9uZTtcbn1cbiIsInhtbCI6Ijx0ZW1wbGF0ZXM+XG4gIDx0IHQtbmFtZT1cInN1YnRlbXBsYXRlXCI+XG4gICAgPHQgdC1zZXQ9XCJfdmFsXCIgdC12YWx1ZT1cInZhbFwiLz5cbiAgICA8QSBnZXRWYWw9XCIoKSA9PiBfdmFsXCIgdC1lc2M9XCJfdmFsXCIvPlxuICA8L3Q+XG4gIFxuICA8dCB0LW5hbWU9XCJBXCI+XG4gICAgPHQgdC1zbG90PVwiZGVmYXVsdFwiLz5cbiAgICA8dCB0LWVzYz1cInByb3BzLmdldFZhbCgpXCIvPlxuICA8L3Q+XG4gIFxuICA8dCB0LW5hbWU9XCJSb290XCI+XG4gICAgPHQgdC1mb3JlYWNoPVwiWzEsIDIsIDNdXCIgdC1hcz1cInZhbFwiIHQta2V5PVwidmFsXCI+XG4gICAgICA8dCB0LWNhbGw9XCJzdWJ0ZW1wbGF0ZVwiLz5cbiAgICAgIDxici8+XG4gICAgICA8QSBnZXRWYWw9XCIoKSA9PiB2YWxcIiB0LWVzYz1cInZhbFwiLz5cbiAgICAgIDxici8+XG4gICAgPC90PlxuICA8L3Q+XG48L3RlbXBsYXRlcz5cbiJ9) of the playground in the previous comment.

To future readers: if you've run into the same problem, please leave a comment and we may revise the decision, especially if the suggested workaround doesn't cover your usecase.
