### ISSUE TITLE
Adding a general term for chasing

### ISSUE THREAD

**Issue by h-mayorquin** [odoo/owl#1514]
So right now the ontology has the two following terms:

```
[Term]
id: NBO:0020040
name: chase prey
def: "Active pursuit of fleeing prey." []
is_a: NBO:0020292 ! capturing behaviour
disjoint_from: NBO:0020045 ! flush prey
created_by: Luke Slater

[Term]
id: NBO:0020141
name: agonistic chase
def: "Chasing of one animal by another during an agonistic conflict." []
is_a: NBO:0000121 ! agonistic behavior
created_by: Luke Slater
```

Now, I am reading the following paper:
Oxytocin neurons enable social transmission of maternal behaviour
https://doi.org/10.1038/s41586-021-03814-7

In the paper, a more experienced female mice (dam) chases a younger female mice with no experience (virgin) back to a litter. You can check about the video of the behavior here:

https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03814-7/MediaObjects/41586_2021_3814_MOESM7_ESM.mp4

I am wondering, this indeed a type of chase but I am not sure it clasifies as "agonistic chase" and efinitly not "chase prey". That is, the terms above seem overly precise. Would it make sense to have a general chase behavior that is parent two the terms above without specifying the context of the chase? Is there a better term in the ontology for this that I am not aware of?

**Comment by ged-odoo** [comment]
Dear @h-mayorquin 
I suspect you meant to open an issue on a project related to the web ontology language. In that case, you got the wrong repository. This repository is about a web framework in javascript.

**Comment by h-mayorquin** [comment]
@ged-odoo 
Totally, sorry for this. Wrong tab when I  absentmindley published!
