### ISSUE TITLE
integrate owl and 3D js libraries

### ISSUE THREAD

**Issue by j209** [odoo/owl#1566]
Is it possible to integrate Owl and [Three.js](https://github.com/mrdoob/three.js) like integration between react and three.js in [R3F](https://github.com/pmndrs/react-three-fiber)?

**Comment by sdegueldre** [comment]
It seems likely that it's possible, but we won't be investing our time into writing or supporting such an integration, much in the same way that the React team doesn't directly support react-three-fiber. It's out of scope for this project.
