### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by j209** [odoo/owl#1582]
Can we say odoo is a fullstack framework that uses owl in frontend and python in backend?

**Comment by sdegueldre** [comment]
Sure. Please note that this repo is about Owl specifically and in particular for technical issues with Owl itself, such as bugs with Owl itself or the playground and devtools, incorrect or incomplete documentation, or the Owl ecosystem outside of Odoo, and that this is not the right place to this type of question.

Please direct questions that are not technical in nature or not specifically about Owl towards the odoo forum.
