### ISSUE TITLE
Problem while using of useService

### ISSUE THREAD

**Issue by jujuna** [odoo/owl#1583]
I am making web client from zero through tutorial of **OXP** but I have this error when I use ```useService```
**Uncaught (in promise) Error: An error occured in the owl lifecycle (see this Error's "cause" property)**

this is my assets code
```
    'assets': {
        'university_library.assets': [
            # bootstrap
            ('include', 'web._assets_helpers'),
            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',
            ('include', 'web._assets_bootstrap_backend'),

            # required for fa icons
            'web/static/src/libs/fontawesome/css/font-awesome.css',

            # include base files from framework
            ('include', 'web._assets_core'),

            # remove some files that we do not use to create a minimal bundle
            # ('remove', 'web/static/src/core/**/*'),
            # ('remove', 'web/static/lib/luxon/luxon.js'),
            'web/static/src/core/utils/functions.js',
            'web/static/src/core/browser/browser.js',
            'web/static/src/core/registry.js',
            'web/static/src/core/assets.js',
            'university_library/static/src/**/*',
        ],
    },
```

and small js code

```/** @odoo-module */

import {Component, useState} from "@odoo/owl";
import {useService} from "@web/core/utils/hooks";

// import {onWillStart, onWillRender, onMounted, onRendered, useRef} from "@odoo/owl";

export class Libraries extends Component {
    static template = 'university_library.Library'

    setup() {
        super.setup();
        this.orm = useService("orm");
    }

}

**Comment by fdardenne** [comment]
Hello 👋 ,

Your error message is quite generic and does not provide the full details of the error. 
Therefore, I cannot provide you with a precise solution. However, I believe that the error may be due to the fact that you need to start the services with await `startServices(env);` before mounting the Owl app. You can refer to an example of how I did this in a standalone app at https://github.com/fdardenne/owlybook/blob/main/static/src/js/main.js”. 

PS: you don't need to call `super.setup()` in the `setup()` method. The `Component` class does not implement any logic in this method.

I hope this helps!

**Comment by flotho** [comment]
hi @jujuna 
maybe the answer is ther https://github.com/odoo/owl/issues/1564

**Comment by flotho** [comment]
hi @jujuna 
maybe the answer is ther https://github.com/odoo/owl/issues/1564

**Comment by flotho** [comment]
@jujuna  which Odoo version are you working with ?
I personnaly struggling on v16 https://github.com/odoo/odoo/issues/151490

**Comment by jujuna** [comment]
@flotho I am working on 17 version, I will see your link if it helps me, thank you!

**Comment by flotho** [comment]
as recommended for v17, use mountcomponent instead, it will work easier

**Comment by flotho** [comment]
Hi @fdardenne does the code you shared woks with services ?

**Comment by fdardenne** [comment]
> Hi @fdardenne does the code you shared woks with services ?

Hello, yes it should

**Comment by flotho** [comment]
I meant does your code effectively worked or did you expect it to work ?

**Comment by jujuna** [comment]
@flotho Thank you! I used ```mountComponent``` and it works.

**Comment by flotho** [comment]
is it a standalone component ?

**Comment by jujuna** [comment]
@flotho Yes

**Comment by flotho** [comment]
perfect, everything is clear.
MAybe this issue could be closed ?

**Comment by abdulrehmanjaved-1** [comment]
getting  this error, I am confused as I have deployed odoo17 as docker container:
when i click on contacts module i get:

`UncaughtPromiseError > OwlError
Uncaught Promise > An error occured in the owl lifecycle (see this Error's "cause" property)
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:9163:35)
        at App.handleError (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:13362:20)
        at ComponentNode.initiateRender (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:9959:26)

Caused by: TypeError: Cannot read properties of undefined (reading 'type')
    at https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:95122:77
    at visit (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:42188:41)
    at visitChildren (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:42184:21)
    at visit (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:42190:17)
    at visitXML (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:42195:5)
    at KanbanArchParser.parse (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:95086:9)
    at Object.props (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:97765:43)
    at View.loadView (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:104606:48)
    at async Promise.all (index 0)
    at async ComponentNode.initiateRender (https://odoo.a3d.nz/web/assets/debug/web.assets_web.js:9956:17)`
    
    
    Appreciated your help. Thanks

**Comment by abdulrehmanjaved-1** [comment]
I have tried regenerating assets way

**Comment by flotho** [comment]
please open a new issue, this one is closed form so long

**Comment by sdegueldre** [comment]
this shouldn't need to be said but closed issues are not the place to discuss entirely different issues.
