### ISSUE TITLE
[perf] props (reactive object) should not be observed outside of rendering

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#1601]
**What is observed?**
Reactive props are always observed, even if they are used outside of the render.

**Why is it bad?**
This leads to extra renders when the value changes, which can be problematic for performance if the render is costly or happening many times.

**Solution?**
When the value of a props is used outside of rendering, it should not be observed and its change should not trigger a re-render.

**Example**
[playground](https://odoo.github.io/owl/playground/#eyJqcyI6ImltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50LCBvbldpbGxSZW5kZXIgfSBmcm9tIFwiQG9kb28vb3dsXCI7XG5cbmNsYXNzIEdyZWV0ZXIgZXh0ZW5kcyBDb21wb25lbnQge1xuICAgIHN0YXRpYyB0ZW1wbGF0ZSA9IFwiR3JlZXRlclwiO1xuICAgIFxuICAgIHNldHVwKCkge1xuICAgICAgICB0aGlzLnJlbmRlckNvdW50ID0gMDtcbiAgICAgICAgb25XaWxsUmVuZGVyKCgpID0+IHsgdGhpcy5yZW5kZXJDb3VudCsrIH0pOyAvLyB0byBub3RpY2UgdGhlcmUgaXMgYW4gZXh0cmEgcmVuZGVyIChpdCB3aWxsIHByaW50IDIpXG4gICAgICAgIHNldFRpbWVvdXQoKCkgPT4gdGhpcy5wcm9wcy5vYmoubmFtZSwgMTUwKTsgLy8gYWNjZXNzaW5nIHZhbHVlIG91dHNpZGUgb2YgcmVuZGVyXG4gICAgfVxufVxuXG4vLyBNYWluIHJvb3QgY29tcG9uZW50XG5jbGFzcyBSb290IGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgY29tcG9uZW50cyA9IHsgR3JlZXRlciB9O1xuICAgIHN0YXRpYyB0ZW1wbGF0ZSA9IFwiUm9vdFwiXG5cbiAgICBzZXR1cCgpIHtcbiAgICAgICAgdGhpcy5zdGF0ZSA9IHVzZVN0YXRlKHsgb2JqOiB7IG5hbWU6ICdIaSd9IH0pO1xuICAgICAgICBzZXRUaW1lb3V0KCgpID0+IHRoaXMuc3RhdGUub2JqLm5hbWUgPSBcIkhlbGxvXCIsIDMwMCk7IC8vIGNoYW5naW5nIHZhbHVlLCBhZnRlciBpdCB3YXMgYWNjZXNzZWQgb3V0c2lkZSBvZiByZW5kZXIgaW4gY2hpbGRcbiAgICB9XG4gICAgXG59XG5cbm1vdW50KFJvb3QsIGRvY3VtZW50LmJvZHksIHsgdGVtcGxhdGVzOiBURU1QTEFURVMsIGRldjogdHJ1ZSB9KTsiLCJjc3MiOiIiLCJ4bWwiOiI8dGVtcGxhdGVzPlxuICA8ZGl2IHQtbmFtZT1cIkdyZWV0ZXJcIj5cbiAgICA8dCB0LWVzYz1cInJlbmRlckNvdW50XCIvPlxuICA8L2Rpdj5cblxuICA8dCB0LW5hbWU9XCJSb290XCI+XG4gICAgPEdyZWV0ZXIgb2JqPVwic3RhdGUub2JqXCIvPlxuICA8L3Q+XG48L3RlbXBsYXRlcz5cbiJ9)

Prints: `1`, then `2`
Expected: only `1`

```js
import { Component, useState, mount, onWillRender } from "@odoo/owl";

class Greeter extends Component {
    static template = "Greeter";
    
    setup() {
        this.renderCount = 0;
        onWillRender(() => { this.renderCount++ }); // to notice there is an extra render (it will print 2)
        setTimeout(() => this.props.obj.name, 150); // accessing value outside of render
    }
}

// Main root component
class Root extends Component {
    static components = { Greeter };
    static template = "Root"

    setup() {
        this.state = useState({ obj: { name: 'Hi'} });
        setTimeout(() => this.state.obj.name = "Hello", 300); // changing value, after it was accessed outside of render in child
    }
    
}

mount(Root, document.body, { templates: TEMPLATES, dev: true });
```

```xml
<templates>
  <div t-name="Greeter">
    <t t-esc="renderCount"/>
  </div>

  <t t-name="Root">
    <Greeter obj="state.obj"/>
  </t>
</templates>
```

**Comment by ged-odoo** [comment]
yep, we know, and i think that we agree.

**Comment by seb-odoo** [comment]
duplicate https://github.com/odoo/owl/issues/1574 ?

**Comment by ged-odoo** [comment]
good catch. yes, exactly. closing this then. Thanks for caring enough to make an issue
