### ISSUE TITLE
How to do routing in owl js version 2.2.10 because router import gives undefined

### ISSUE THREAD

**Issue by Hamzaansari15** [odoo/owl#1602]

**Comment by sdegueldre** [comment]
The router is no longer a part of Owl as it doesn't require access to Owl internals to implement, it can be implemented in user code. Here is an example implementation in Odoo:

https://github.com/odoo/odoo/blob/17.0/addons/pos_self_order/static/src/app/router.js
https://github.com/odoo/odoo/blob/17.0/addons/pos_self_order/static/src/app/self_order_index.xml

**Comment by hamza-strugbits** [comment]
So, I write all mention code for creating route in owl
