### ISSUE TITLE
Please explain how to do routing in owl js 

### ISSUE THREAD

**Issue by hamza-strugbits** [odoo/owl#1603]
Explain how to import route from owl module our do write all this code for routing 
https://github.com/odoo/odoo/blob/17.0/addons/pos_self_order/static/src/app/router.js
https://github.com/odoo/odoo/blob/17.0/addons/pos_self_order/static/src/app/self_order_index.xml

**Comment by sdegueldre** [comment]
This is not a support forum, the issues on this repo are for reporting bugs with Owl or its documentation. If you need help direct your questions to the Odoo forum or third party discussion spaces. I've already given you pointers in case you'd like to implement routing yourself.
