### ISSUE TITLE
Options in component "SelectMenu" overflow

### ISSUE THREAD

**Issue by Devryc** [odoo/owl#1625]
Hi,

Odoo version 17 from Docker
I'm using the SelectMenu component from @web/core/select_menu/select_menu following the [documentation](@web/core/select_menu/select_menu). 
I fill the choices with 414 items and when I opened he overflowed.

![image](https://github.com/odoo/owl/assets/86820788/9f025fd7-1ff4-4abb-a98a-16f7b489a1a6)

**Comment by sdegueldre** [comment]
This repo is for Owl, not Odoo. Issues with odoo should be reported on the odoo repository or through odoo support.

**Comment by Devryc** [comment]
This is a component from Owl
