### ISSUE TITLE
Search in component "SelectMenu" doesn't work properly

### ISSUE THREAD

**Issue by Devryc** [odoo/owl#1626]
Hi,

Odoo version 17 from Docker.
When I try search in a SelectMenu component, he seems to looking for every single **letter** and not for **word**.

Those are some examples:
Search: `Infantil`
![image](https://github.com/odoo/owl/assets/86820788/cb57a73b-515e-4e44-ace5-9b7025d964be)

Search: `Matemáticas`
![image](https://github.com/odoo/owl/assets/86820788/652f97b1-4ff1-4d88-a6b6-bc05eb30bbcd)

It's seem to search letter by letter in order to appear. In second image you can see in results: 
"Ingeniería Infor|**mát**|ica-T|**e**|cnologías Infor|**máticas**|"

**Comment by sdegueldre** [comment]
This repo is for Owl, not Odoo. Issues with odoo should be reported on the odoo repository or through odoo support.

**Comment by Devryc** [comment]
This is a component from Owl.

**Comment by Devryc** [comment]
What a maze. 

My apologize
