### ISSUE TITLE
Error: Invalid object: unknown key 'template', 'component' is missing

### ISSUE THREAD

**Issue by okb1100** [odoo/owl#1649]
I'm not sure if that's an odoo or owl issue, but I get the following error when migrating from odoo 16 to 18.

I'd love to know how odoo and owl versions relate to each other so I get a better understanding on how this framework is integrated to odoo itself.

```console
Uncaught Error: Error while loading "@voice_generation/js/audio_player":
Error: Invalid object: unknown key 'template', 'component' is missing
    startModule http://127.0.0.1:18069/web/assets/1dca19f/web.assets_web.min.js:17
    startModules http://127.0.0.1:18069/web/assets/1dca19f/web.assets_web.min.js:16
    addJob http://127.0.0.1:18069/web/assets/1dca19f/web.assets_web.min.js:13
    define http://127.0.0.1:18069/web/assets/1dca19f/web.assets_web.min.js:12
    <anonymous> http://127.0.0.1:18069/web/assets/1dca19f/web.assets_web.min.js:23102
```

Here's the component: 

```javascript
/** @odoo-module **/

import {xml, Component, useState} from "@odoo/owl";
import {registry} from "@web/core/registry";

export class AudioPlayer extends Component {
  setup() {
    console.log(this.props);
    this.state = useState({url: "/api/voice/play/" + this.props.record.data.id});
  }
}

AudioPlayer.template = xml`<audio controls="controls" t-att-src="state.url">
Your browser does not support the audio element.
</audio>`;

registry.category("fields").add("AudioPlayer", AudioPlayer);
```

here's the xml call from inside odoo
```xml
<field name="text" widget="voice_generation.AudioPlayer"/>
```

This module worked perfectly fine on odoo 16. Again, willing to learn what changed since because odoo docs don't have a "breaking changes" section.

I've also asked this over at the [odoo forums](https://www.odoo.com/forum/help-1/error-invalid-object-unknown-key-template-component-is-missing-265836) but no luck there

**Comment by ged-odoo** [comment]
this is not owl related, but web framework. The reason for your crash is that the fields registry  did change, it now requires an object with a `component` key. The error message that you see comes from the registry validation system.

So, in your case, you probably need to do something like this:
```js
registry.category("fields").add("AudioPlayer", {
  component: AudioPlayer
});

```

**Comment by OmarZaatari** [comment]
Hello, the odoo 18.0 docs don't mention this new requirement :(

**Comment by sdegueldre** [comment]
@OmarZaatari then you can open an issue on the documentation project. This is not an owl issue.
