### ISSUE TITLE
Error: Unknown QWeb directive: 't-props' in <button>

### ISSUE THREAD

**Issue by picolo-mrchs** [odoo/owl#1653]
I'm trying to do a simple button with a rippling effect, and allow any prop to be passed from the caller to the `button`.

When I try to use [`t-props`](https://github.com/odoo/owl/blob/26c7856d5d8a83a297569614dce2d96e0627dd88/doc/reference/props.md#dynamic-props), like this:

```xml
<templates>
  <t t-name="BasicButton">
    <div class="BasicButton">
      <button t-ref="button" t-props="props">
        <t t-slot="default">Button</t>
      </button>
    </div>
  </t>
</templates>
```

The app fails with  

```
Uncaught (in promise) Error: Unknown QWeb directive: 't-props'
```

Playground Link: [Failing version](https://odoo.github.io/owl/playground/#eyJqcyI6ImltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIHVzZVJlZiwgbW91bnQsIG9uTW91bnRlZCwgb25XaWxsVW5tb3VudCB9IGZyb20gXCJAb2Rvby9vd2xcIjtcblxuICAgIGNsYXNzIEJhc2ljQnV0dG9uIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICAgICAgc3RhdGljIHRlbXBsYXRlID0gXCJCYXNpY0J1dHRvblwiO1xuICAgICAgICBzdGF0aWMgcHJvcHM9W1wiKlwiXTtcblxuICAgICAgICBidXR0b25SZWYgPSB1c2VSZWYoXCJidXR0b25cIik7XG5cbiAgICAgICAgc2V0dXAoKSB7XG4gICAgICAgICAgICBvbk1vdW50ZWQoKCkgPT4ge1xuICAgICAgICAgICAgICAgIGNvbnN0IGJ1dHRvbiA9IHRoaXMuYnV0dG9uUmVmLmVsO1xuICAgICAgICAgICAgICAgIGJ1dHRvbi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgdGhpcy5hZGRSaXBwbGUuYmluZCh0aGlzKSk7XG4gICAgICAgICAgICB9KTtcblxuICAgICAgICAgICAgb25XaWxsVW5tb3VudCgoKSA9PiB7XG4gICAgICAgICAgICAgICAgY29uc3QgYnV0dG9uID0gdGhpcy5idXR0b25SZWYuZWw7XG4gICAgICAgICAgICAgICAgYnV0dG9uLnJlbW92ZUV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCB0aGlzLmFkZFJpcHBsZS5iaW5kKHRoaXMpKTtcbiAgICAgICAgICAgIH0pO1xuICAgICAgICB9XG5cbiAgICAgICAgLyoqXG4gICAgICAgICAqIEFkZCByaXBwbGUgZWZmZWN0IHRvIHRoZSBidXR0b24gY2xpY2sgZXZlbnRcbiAgICAgICAgICovXG4gICAgICAgIGFkZFJpcHBsZShldmVudCkge1xuICAgICAgICAgICAgY29uc3QgYnV0dG9uID0gdGhpcy5idXR0b25SZWYuZWw7XG4gICAgICAgICAgICBjb25zb2xlLmRlYnVnKFwiUmlwcGxlXCIsIGV2ZW50LCBidXR0b24pO1xuXG4gICAgICAgICAgICAvLyBSZW1vdmUgYW55IGV4aXN0aW5nIHJpcHBsZSBzcGFucyB0byBhdm9pZCBzdGFja2luZ1xuICAgICAgICAgICAgY29uc3Qgb2xkUmlwcGxlID0gYnV0dG9uLnF1ZXJ5U2VsZWN0b3IoXCJzcGFuLnJpcHBsZVwiKTtcbiAgICAgICAgICAgIGlmIChvbGRSaXBwbGUpIG9sZFJpcHBsZS5yZW1vdmUoKTtcblxuICAgICAgICAgICAgLy8gQ3JlYXRlIGEgc3BhbiBlbGVtZW50IGZvciB0aGUgcmlwcGxlXG4gICAgICAgICAgICBjb25zdCByaXBwbGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KFwic3BhblwiKTtcbiAgICAgICAgICAgIHJpcHBsZS5jbGFzc05hbWUgPSBcInJpcHBsZVwiO1xuXG4gICAgICAgICAgICAvLyBDYWxjdWxhdGUgdGhlIHBvc2l0aW9uIGZvciB0aGUgcmlwcGxlXG4gICAgICAgICAgICBjb25zdCByZWN0ID0gYnV0dG9uLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuICAgICAgICAgICAgY29uc3Qgc2l6ZSA9IE1hdGgubWF4KHJlY3Qud2lkdGgsIHJlY3QuaGVpZ2h0KTtcbiAgICAgICAgICAgIHJpcHBsZS5zdHlsZS53aWR0aCA9IHJpcHBsZS5zdHlsZS5oZWlnaHQgPSBgJHtzaXplfXB4YDtcblxuICAgICAgICAgICAgLy8gUG9zaXRpb24gdGhlIHJpcHBsZSBhdCB0aGUgY2xpY2sgcG9pbnRcbiAgICAgICAgICAgIGNvbnN0IHRvcCA9IGV2ZW50LmNsaWVudFkgLSByZWN0LnRvcCAtIHNpemUgLyAyO1xuICAgICAgICAgICAgY29uc3QgbGVmdCA9IGV2ZW50LmNsaWVudFggLSByZWN0LmxlZnQgLSBzaXplIC8gMjtcbiAgICAgICAgICAgIHJpcHBsZS5zdHlsZS50b3AgPSBgJHt0b3B9cHhgO1xuICAgICAgICAgICAgcmlwcGxlLnN0eWxlLmxlZnQgPSBgJHtsZWZ0fXB4YDtcblxuICAgICAgICAgICAgLy8gQWRkIHRoZSByaXBwbGUgdG8gdGhlIGJ1dHRvblxuICAgICAgICAgICAgYnV0dG9uLmFwcGVuZENoaWxkKHJpcHBsZSk7XG5cbiAgICAgICAgICAgIC8vIFJlbW92ZSB0aGUgcmlwcGxlIGFmdGVyIGFuaW1hdGlvbiBlbmRzXG4gICAgICAgICAgICByaXBwbGUuYWRkRXZlbnRMaXN0ZW5lcihcImFuaW1hdGlvbmVuZFwiLCAoKSA9PiB7XG4gICAgICAgICAgICAgICAgY29uc29sZS5kZWJ1ZyhcIlJlbW92aW5nIHJpcHBsZVwiKTtcbiAgICAgICAgICAgICAgICByaXBwbGUucmVtb3ZlKCk7XG4gICAgICAgICAgICB9KTtcbiAgICAgICAgfVxuICAgIH1cblxuLy8gQXBwbGljYXRpb24gc2V0dXBcbm1vdW50KEJhc2ljQnV0dG9uLCBkb2N1bWVudC5ib2R5LCB7IHRlbXBsYXRlczogVEVNUExBVEVTLCBkZXY6IHRydWUgfSk7XG4iLCJjc3MiOiIvKiBSaXBwbGUgYW5pbWF0aW9uICovXG5Aa2V5ZnJhbWVzIGJhc2ljLWJ1dHRvbi1yaXBwbGUtYW5pbWF0aW9uIHtcbiAgICBmcm9tIHtcbiAgICAgICAgdHJhbnNmb3JtOiBzY2FsZSgwKTtcbiAgICAgICAgb3BhY2l0eTogMTtcbiAgICB9XG4gICAgdG8ge1xuICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDQpO1xuICAgICAgICBvcGFjaXR5OiAwO1xuICAgIH1cbn1cblxuLkJhc2ljQnV0dG9uIHtcbiAgICBidXR0b24ge1xuICAgICAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgICAgIG92ZXJmbG93OiBoaWRkZW47IC8qIEVuc3VyZSByaXBwbGUgc3RheXMgd2l0aGluIGJvdW5kcyAqL1xuICAgICAgICBwYWRkaW5nOiB2YXIoLS1idXR0b24tcGFkZGluZywgMTBweCAzMHB4KTtcbiAgICAgICAgdGV4dC10cmFuc2Zvcm06IHZhcigtLWJ1dHRvbi10ZXh0LXRyYW5zZm9ybSwgdXBwZXJjYXNlKTtcbiAgICAgICAgZm9udC13ZWlnaHQ6IHZhcigtLWJ1dHRvbi1mb250LXdlaWdodCwgNzAwKTtcbiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKFxuICAgICAgICAgICAgLS1idXR0b24tYmFja2dyb3VuZC1jb2xvciwgIzQwZDllOFxuICAgICAgICApO1xuICAgICAgICBib3JkZXI6IHZhcigtLWJ1dHRvbi1ib3JkZXIsIG5vbmUpO1xuICAgICAgICBib3JkZXItcmFkaXVzOiB2YXIoLS1idXR0b24tYm9yZGVyLXJhZGl1cywgNXB4KTtcbiAgICAgICAgY29sb3I6IHZhcigtLWJ1dHRvbi1jb2xvciwgI2ZmZik7XG4gICAgICAgIGN1cnNvcjogcG9pbnRlcjtcbiAgICB9XG5cbiAgICBidXR0b246aG92ZXIge1xuICAgICAgICBjb2xvcjogdmFyKC0tYnV0dG9uLWhvdmVyLWNvbG9yLCAjMDAwKTtcbiAgICB9XG5cbiAgICAvKiBSaXBwbGUgZWZmZWN0ICovXG4gICAgYnV0dG9uIC5yaXBwbGUge1xuICAgICAgICBkaXNwbGF5OiBibG9jaztcbiAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgICBib3JkZXItcmFkaXVzOiA1MCU7XG4gICAgICAgIGJhY2tncm91bmQ6IHZhcigtLWJ1dHRvbi1yaXBwbGUtYmcsIHJnYmEoMDAsIDkxLCAyMjcsIDAuMykpO1xuICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDApO1xuICAgICAgICBwb2ludGVyLWV2ZW50czogbm9uZTtcbiAgICAgICAgYW5pbWF0aW9uOiBiYXNpYy1idXR0b24tcmlwcGxlLWFuaW1hdGlvbiAwLjZzIGVhc2Utb3V0O1xuICAgIH1cbn1cbiIsInhtbCI6Ijx0ZW1wbGF0ZXM+XG4gIDx0IHQtbmFtZT1cIkJhc2ljQnV0dG9uXCI+XG4gICAgPGRpdiBjbGFzcz1cIkJhc2ljQnV0dG9uXCI+XG4gICAgICA8YnV0dG9uIHQtcmVmPVwiYnV0dG9uXCIgdC1wcm9wcz1cInByb3BzXCI+XG4gICAgICAgIDx0IHQtc2xvdD1cImRlZmF1bHRcIj5CdXR0b248L3Q+XG4gICAgICA8L2J1dHRvbj5cbiAgICA8L2Rpdj5cbiAgPC90PlxuPC90ZW1wbGF0ZXM+XG4ifQ==)

If I remove the `t-props`, the button works but I cannot pass any props to the button.  

Playground Link: [Working without `t-props`](https://odoo.github.io/owl/playground/#eyJqcyI6ImltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIHVzZVJlZiwgbW91bnQsIG9uTW91bnRlZCwgb25XaWxsVW5tb3VudCB9IGZyb20gXCJAb2Rvby9vd2xcIjtcblxuICAgIGNsYXNzIEJhc2ljQnV0dG9uIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICAgICAgc3RhdGljIHRlbXBsYXRlID0gXCJCYXNpY0J1dHRvblwiO1xuICAgICAgICBzdGF0aWMgcHJvcHM9W1wiKlwiXTtcblxuICAgICAgICBidXR0b25SZWYgPSB1c2VSZWYoXCJidXR0b25cIik7XG5cbiAgICAgICAgc2V0dXAoKSB7XG4gICAgICAgICAgICBvbk1vdW50ZWQoKCkgPT4ge1xuICAgICAgICAgICAgICAgIGNvbnN0IGJ1dHRvbiA9IHRoaXMuYnV0dG9uUmVmLmVsO1xuICAgICAgICAgICAgICAgIGJ1dHRvbi5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgdGhpcy5hZGRSaXBwbGUuYmluZCh0aGlzKSk7XG4gICAgICAgICAgICB9KTtcblxuICAgICAgICAgICAgb25XaWxsVW5tb3VudCgoKSA9PiB7XG4gICAgICAgICAgICAgICAgY29uc3QgYnV0dG9uID0gdGhpcy5idXR0b25SZWYuZWw7XG4gICAgICAgICAgICAgICAgYnV0dG9uLnJlbW92ZUV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCB0aGlzLmFkZFJpcHBsZS5iaW5kKHRoaXMpKTtcbiAgICAgICAgICAgIH0pO1xuICAgICAgICB9XG5cbiAgICAgICAgLyoqXG4gICAgICAgICAqIEFkZCByaXBwbGUgZWZmZWN0IHRvIHRoZSBidXR0b24gY2xpY2sgZXZlbnRcbiAgICAgICAgICovXG4gICAgICAgIGFkZFJpcHBsZShldmVudCkge1xuICAgICAgICAgICAgY29uc3QgYnV0dG9uID0gdGhpcy5idXR0b25SZWYuZWw7XG4gICAgICAgICAgICBjb25zb2xlLmRlYnVnKFwiUmlwcGxlXCIsIGV2ZW50LCBidXR0b24pO1xuXG4gICAgICAgICAgICAvLyBSZW1vdmUgYW55IGV4aXN0aW5nIHJpcHBsZSBzcGFucyB0byBhdm9pZCBzdGFja2luZ1xuICAgICAgICAgICAgY29uc3Qgb2xkUmlwcGxlID0gYnV0dG9uLnF1ZXJ5U2VsZWN0b3IoXCJzcGFuLnJpcHBsZVwiKTtcbiAgICAgICAgICAgIGlmIChvbGRSaXBwbGUpIG9sZFJpcHBsZS5yZW1vdmUoKTtcblxuICAgICAgICAgICAgLy8gQ3JlYXRlIGEgc3BhbiBlbGVtZW50IGZvciB0aGUgcmlwcGxlXG4gICAgICAgICAgICBjb25zdCByaXBwbGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KFwic3BhblwiKTtcbiAgICAgICAgICAgIHJpcHBsZS5jbGFzc05hbWUgPSBcInJpcHBsZVwiO1xuXG4gICAgICAgICAgICAvLyBDYWxjdWxhdGUgdGhlIHBvc2l0aW9uIGZvciB0aGUgcmlwcGxlXG4gICAgICAgICAgICBjb25zdCByZWN0ID0gYnV0dG9uLmdldEJvdW5kaW5nQ2xpZW50UmVjdCgpO1xuICAgICAgICAgICAgY29uc3Qgc2l6ZSA9IE1hdGgubWF4KHJlY3Qud2lkdGgsIHJlY3QuaGVpZ2h0KTtcbiAgICAgICAgICAgIHJpcHBsZS5zdHlsZS53aWR0aCA9IHJpcHBsZS5zdHlsZS5oZWlnaHQgPSBgJHtzaXplfXB4YDtcblxuICAgICAgICAgICAgLy8gUG9zaXRpb24gdGhlIHJpcHBsZSBhdCB0aGUgY2xpY2sgcG9pbnRcbiAgICAgICAgICAgIGNvbnN0IHRvcCA9IGV2ZW50LmNsaWVudFkgLSByZWN0LnRvcCAtIHNpemUgLyAyO1xuICAgICAgICAgICAgY29uc3QgbGVmdCA9IGV2ZW50LmNsaWVudFggLSByZWN0LmxlZnQgLSBzaXplIC8gMjtcbiAgICAgICAgICAgIHJpcHBsZS5zdHlsZS50b3AgPSBgJHt0b3B9cHhgO1xuICAgICAgICAgICAgcmlwcGxlLnN0eWxlLmxlZnQgPSBgJHtsZWZ0fXB4YDtcblxuICAgICAgICAgICAgLy8gQWRkIHRoZSByaXBwbGUgdG8gdGhlIGJ1dHRvblxuICAgICAgICAgICAgYnV0dG9uLmFwcGVuZENoaWxkKHJpcHBsZSk7XG5cbiAgICAgICAgICAgIC8vIFJlbW92ZSB0aGUgcmlwcGxlIGFmdGVyIGFuaW1hdGlvbiBlbmRzXG4gICAgICAgICAgICByaXBwbGUuYWRkRXZlbnRMaXN0ZW5lcihcImFuaW1hdGlvbmVuZFwiLCAoKSA9PiB7XG4gICAgICAgICAgICAgICAgY29uc29sZS5kZWJ1ZyhcIlJlbW92aW5nIHJpcHBsZVwiKTtcbiAgICAgICAgICAgICAgICByaXBwbGUucmVtb3ZlKCk7XG4gICAgICAgICAgICB9KTtcbiAgICAgICAgfVxuICAgIH1cblxuLy8gQXBwbGljYXRpb24gc2V0dXBcbm1vdW50KEJhc2ljQnV0dG9uLCBkb2N1bWVudC5ib2R5LCB7IHRlbXBsYXRlczogVEVNUExBVEVTLCBkZXY6IHRydWUgfSk7XG4iLCJjc3MiOiIvKiBSaXBwbGUgYW5pbWF0aW9uICovXG5Aa2V5ZnJhbWVzIGJhc2ljLWJ1dHRvbi1yaXBwbGUtYW5pbWF0aW9uIHtcbiAgICBmcm9tIHtcbiAgICAgICAgdHJhbnNmb3JtOiBzY2FsZSgwKTtcbiAgICAgICAgb3BhY2l0eTogMTtcbiAgICB9XG4gICAgdG8ge1xuICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDQpO1xuICAgICAgICBvcGFjaXR5OiAwO1xuICAgIH1cbn1cblxuLkJhc2ljQnV0dG9uIHtcbiAgICBidXR0b24ge1xuICAgICAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgICAgIG92ZXJmbG93OiBoaWRkZW47IC8qIEVuc3VyZSByaXBwbGUgc3RheXMgd2l0aGluIGJvdW5kcyAqL1xuICAgICAgICBwYWRkaW5nOiB2YXIoLS1idXR0b24tcGFkZGluZywgMTBweCAzMHB4KTtcbiAgICAgICAgdGV4dC10cmFuc2Zvcm06IHZhcigtLWJ1dHRvbi10ZXh0LXRyYW5zZm9ybSwgdXBwZXJjYXNlKTtcbiAgICAgICAgZm9udC13ZWlnaHQ6IHZhcigtLWJ1dHRvbi1mb250LXdlaWdodCwgNzAwKTtcbiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogdmFyKFxuICAgICAgICAgICAgLS1idXR0b24tYmFja2dyb3VuZC1jb2xvciwgIzQwZDllOFxuICAgICAgICApO1xuICAgICAgICBib3JkZXI6IHZhcigtLWJ1dHRvbi1ib3JkZXIsIG5vbmUpO1xuICAgICAgICBib3JkZXItcmFkaXVzOiB2YXIoLS1idXR0b24tYm9yZGVyLXJhZGl1cywgNXB4KTtcbiAgICAgICAgY29sb3I6IHZhcigtLWJ1dHRvbi1jb2xvciwgI2ZmZik7XG4gICAgICAgIGN1cnNvcjogcG9pbnRlcjtcbiAgICB9XG5cbiAgICBidXR0b246aG92ZXIge1xuICAgICAgICBjb2xvcjogdmFyKC0tYnV0dG9uLWhvdmVyLWNvbG9yLCAjMDAwKTtcbiAgICB9XG5cbiAgICAvKiBSaXBwbGUgZWZmZWN0ICovXG4gICAgYnV0dG9uIC5yaXBwbGUge1xuICAgICAgICBkaXNwbGF5OiBibG9jaztcbiAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgICBib3JkZXItcmFkaXVzOiA1MCU7XG4gICAgICAgIGJhY2tncm91bmQ6IHZhcigtLWJ1dHRvbi1yaXBwbGUtYmcsIHJnYmEoMDAsIDkxLCAyMjcsIDAuMykpO1xuICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDApO1xuICAgICAgICBwb2ludGVyLWV2ZW50czogbm9uZTtcbiAgICAgICAgYW5pbWF0aW9uOiBiYXNpYy1idXR0b24tcmlwcGxlLWFuaW1hdGlvbiAwLjZzIGVhc2Utb3V0O1xuICAgIH1cbn1cbiIsInhtbCI6Ijx0ZW1wbGF0ZXM+XG4gIDx0IHQtbmFtZT1cIkJhc2ljQnV0dG9uXCI+XG4gICAgPGRpdiBjbGFzcz1cIkJhc2ljQnV0dG9uXCI+XG4gICAgICA8YnV0dG9uIHQtcmVmPVwiYnV0dG9uXCI+XG4gICAgICAgIDx0IHQtc2xvdD1cImRlZmF1bHRcIj5CdXR0b248L3Q+XG4gICAgICA8L2J1dHRvbj5cbiAgICA8L2Rpdj5cbiAgPC90PlxuPC90ZW1wbGF0ZXM+XG4ifQ==)

**Comment by kebeclibre** [comment]
The directive t-props is only valid on component nodes, not on html nodes
```xml
<t t-name="Parent">
   <MyComponent t-props="this.myProps" />
</t>
 ```

**Comment by sdegueldre** [comment]
if you need dynamic attributes on a node you can use a bare `t-att="objectWithAttributes"`, as described here: https://github.com/odoo/owl/blob/master/doc/reference/templates.md#dynamic-attributes
