### ISSUE TITLE
make owl available on npm

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#196]
This should obviously only be done once owl is officially public.

This would help starting new projects with owl...

**Comment by aadrian** [comment]
@ged-odoo is it public now? Can it be published?

**Comment by ged-odoo** [comment]
@aadrian The owl repository is public, as you can see.  To make it available on npm, I need to check some details, such as how to publish something as an organization, who will be the contact at odoo, that kind of questions.  Also, I was waiting a little bit for Owl to stabilize.  It is almost there, but we need a little bit more time to complete the last bugfixes.

**Comment by aadrian** [comment]
@ged-odoo 

> I need to check some details ...

Thank you for the details.


>  Also, I was waiting a little bit for Owl to stabilize.

I guess since NPM allows to publish beta versions too: `npm publish --tag beta`, Travis CI could do everything automatically: https://docs.travis-ci.com/user/deployment/npm/ .

**Comment by aadrian** [comment]
@ged-odoo thank you for the relase to NPM

**Comment by ged-odoo** [comment]
@aadrian Thank you for your interest in Owl... If you have ideas for improvement, or if you encounter pain points, don't hesitate to open an issue.
