### ISSUE TITLE
Interleaving connected component local state & store changes

### ISSUE THREAD

**Issue by alexkuhn** [odoo/owl#268]
When a connected component re-renders from a local `state` change, if the store changes at the same time, this component template uses old `storeProps` while sub-components templates use new `storeProps`.

### Steps to reproduce

- Copy-paste code below in playground.
- Click on "Delete" button

It crashes with following error:
```
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
```

Code below crashes because Attachment has been deleted from store while Message re-renders from its local `state`. Attachment is re-rendered by Message instead of being unmounted.
Looks like when the component's local state changes, it still has old `storeProps` in the context, but when `mapStoreToProps` of the child is called, it has the new `storeProps`.

### Code

**JS**
```js
// Store
const actions = {
    async deleteAttachment({ dispatch, state }, attachmentId) {
        await Promise.resolve();
        delete state.attachments[attachmentId];
        for (const message of Object.values(state.messages)) {
            state.messages[message.id].attachmentIds =
                state.messages[message.id].attachmentIds.filter(id =>
                    id !== attachmentId);
        }
    },
};
const state = {
    attachments: {
        100: {
            id: 100,
            name: "text.txt",
        },
    },
    messages: {
        10: {
            attachmentIds: [100],
            id: 10,
        },
    },
};
const store = new owl.store.Store({ actions, state });

// Connected Components
class Attachment extends owl.store.ConnectedComponent {
    static mapStoreToProps(state, ownProps) {
        return {
            name: state.attachments[ownProps.id].name,
        };
    }
    _onClickDelete() {
        this.dispatch('deleteAttachment', this.props.id);
        this.trigger('delete');
    }
}
class Message extends owl.store.ConnectedComponent {
    static mapStoreToProps(state, ownProps) {
        return {
            attachmentIds: state.messages[ownProps.id].attachmentIds,
        };
    }
    components = { Attachment };
    state = {
        isAttachmentDeleted: false,
    };
    _onDeleteAttachment() {
        this.state.isAttachmentDeleted = true;
    }
}

// App
class App extends owl.Component {
    components = { Message };
}
const qweb = new owl.QWeb(TEMPLATES);
const app = new App({ qweb, store });
app.mount(document.body);
```
**XML**
```xml
<templates>
  <div t-name="Attachment" class="attachment">
    <span>Attachment <t t-esc="props.id"/></span>
    <span>Name: <t t-esc="storeProps.name"/></span>
    <button t-on-click="_onClickDelete">Delete</button>
  </div>
  
  <div t-name="Message" class="message">
    <span>Message <t t-esc="props.id"/></span>
    <Attachment t-foreach="storeProps.attachmentIds" t-as="attachmentId" id="attachmentId" t-on-delete="_onDeleteAttachment"/>
  </div>

  <div t-name="App">
    <span>App</span>
    <Message id="10"/>
  </div>
</templates>
```

**Comment by ged-odoo** [comment]
@alexkuhn good news, I could not reproduce this bug in the new store implementation. Hopefully it is fixed. If you encounter any new issue, please open a new issue with as much info as you can!

**Comment by alexkuhn** [comment]
Still have similar issue with v0.23, which has new store implementation.
Do you think https://github.com/odoo/owl/pull/332 will fix all concurrent rendering issues?
I can try and make a small example on playground having this issue again with connected components.

**Comment by ged-odoo** [comment]
I believe that issue #332 will solve lots of tricky issues. I believe that it will correctly handle all concurrency issues. So, yes, wait a little bit before reinvestigating this.
