### ISSUE TITLE
observer: consider creating new reference instead of modify in place 

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#294]
In react world, we tend to create new objects. This could look like this:
```js
  const newState = {...oldState, someKey: newValue};
```

This has the advantage of being able to check by reference equality to know if something has changed or not. As a disadvantage, it is slightly awkward to write update code.

In Vue, we modify in place:
```js
   newState.someKey = newValue;
```
This is much simpler to write, but then it makes it harder to know what has changed and what has not changed.  Vue has to track changes, and has a system to know which component needs which information, so it can rerender only what needs to be rerendered.

Owl started with the React strategy, then moved to Vue strategy (modified).  However, now that we use proxys, maybe there is a way to have the best of both worlds: writing updates in a simple way, and being able to check by reference equality.

To do this, the observer/proxy would simply intercepts the updates and rewrite then as transformations like React.  I am not sure it can work, but we should try...

**Comment by sdegueldre** [comment]
No longer relevant in owl 2
