### ISSUE TITLE
t-keepalive, t-transition and t-asyncroot should be wrapper components (?)

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#295]
It was not possible for a long time, since we did not support wrapper components (components which do not have a root dom node for themselves).

But now, it may be interesting to investigate:
instead of this:
```xml
    <Counter t-if="state.componentFlag" t-transition="fade"/>
```
we could have this:
```xml
    <Animation name="fade" t-if="state.componentFlag">
       <Counter />
    </Animation>
```

Question: is it a good idea? As a pro, it means that we have less directives.  What else?

**Comment by aab-odoo** [comment]
remove t-keepalive for v1

**Comment by aab-odoo** [comment]
Remaining part moved to #429
