### ISSUE TITLE
rethink app initialization

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#306]
Currently, creating a new app looks like this: 

```js
const app = new App({ qweb: new QWeb() });
app.mount(document.body);
```

Maybe there could be an implicit creation of qweb instance if not given:

```js
const app = new App();
app.mount(document.body);
```
So, this simplify the widget constructor signature: it's always `parent, props`.

What if we need a custom environment? Maybe it could optionally be given to `mount`:
```js
const app = new App();
app.mount(document.body, {some: 'thing'});
```

**Comment by ged-odoo** [comment]
Here is an idea:

1. components always take `parent, props` in the constructor. No exception. If there are no parent (such as a root widget), then it needs to be falsy (null or undefined for example)

2. If there are no parent, we construct a default environment with an empty QWeb instance

3. We add a static `registerTemplates` method on QWeb, so we can load templates.
  ```js
   const {QWeb, Component } = owl;
   
  QWeb.registerTemplates(TEMPLATES);
  const app = new App();
  app.mount(document.body);
  ```

4. In the playground, we can make the call to registerTemplate automatically, so the playground code is very simple

5. we rename the `useSubEnv` hook into `useEnv`

6. The `useEnv` directive can be used before creating the first component. In that case, it registers an environment to be used instead of the empty one by default.  Note that if there is no QWeb instance in that env, it will be added automatically.
```js
// app creation
useEnv(myEnv);
const app = new App();
app.mount(document.body);
```

7. Note that technically, the `App` root widget could use `useEnv` itself, but then it would import its environment, which makes it harder to replace with a custom environment for testing, so this would not be ideal.

8. For tests, we could do something like this:
```js
// beforeEach
QWeb.current = null;
QWeb._defaultEnv = null;
let testEnv = makeTestEnvironment();
useEnv(testEnv);
```

**Comment by aab-odoo** [comment]
Rough ideas:
 - remove the (env) API of Component;
   - create an owl.config, which contains 'rootEnv' and 'mode' (moved from `owl.__info__`)
   - before creating the root component, 'config.rootEnv' must be set
```
config.rootEnv = { qweb: new QWeb() };
const app = new App();
```

 - maybe remove the other API (parent, props) as well: this one should only be used internally by the framework, so we could use a small helper to define the parent and props to use just before creating a new sub-component.

 - if we remove this API, we could consider keeping the other one: 'new Component(env)'. 
   - Pros: simpler than setting a rootEnv before instantiating a componing
   - Cons: must *sometimes* pass 'env' as argument when calling _super in constructor (e.g. when using hooks)
