### ISSUE TITLE
playground broken

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#335]
Go to https://odoo.github.io/owl/playground/ and click run:

Result: SyntaxError: bad method definition

**Comment by ged-odoo** [comment]
on firefox I assume?

it looks like it only works with chrome until firefox implement static class fields.

You can make the first example work by replacing

```js
class App extends Component {
    static components = { Greeter };
    state = useState({ name: 'World'});
}
```

with

```js
class App extends Component {
    state = useState({ name: 'World'});
}
App.components = { Greeter };
```

**Comment by ged-odoo** [comment]
I think i will change all examples from the playground to use that syntax for now. Its not as nice, but at least it should work on every browser

**Comment by seb-odoo** [comment]
firefox indeed

**Comment by seb-odoo** [comment]
Your suggestion solved the issue.
