### ISSUE TITLE
doc component typo

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#338]
> described in term**s** of the state

 (should have the "s")

**Comment by seb-odoo** [comment]
> This example show**s** how a component
There too

**Comment by ged-odoo** [comment]
for these typos, you can do a PR!

**Comment by seb-odoo** [comment]
I don't have a repo locally right now so I'm just using these issues to take notes. I can do a PR tomorrow if you prefer.

**Comment by seb-odoo** [comment]
>  small class which represent**s** a component

same

**Comment by seb-odoo** [comment]
> one of its ancestor**s**

**Comment by seb-odoo** [comment]
> hook generate**s** a proxy version of

**Comment by seb-odoo** [comment]
> changed later by the parent, in some case**s**

**Comment by seb-odoo** [comment]
> This property is set to the currently being defined component (in the constructor). 

Strange sentence

**Comment by seb-odoo** [comment]
>  each children need**s** to be created as well

**Comment by seb-odoo** [comment]
> in case a component need**s** to be

**Comment by seb-odoo** [comment]
> Updating the compo**n**ent

**Comment by seb-odoo** [comment]
> See the section on error handling

missing dot at the end
