### ISSUE TITLE
doc components unclear (Reactive system)

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#341]
> OWL components can be made reactive by observing some part of their state.

I don't understand why "some part". It seems to me the whole state is observed, and if it is possible to observe only part of it, it is not specified how to do it.

**Comment by ged-odoo** [comment]
the point is that a component needs to explicitely use the method `useState` to observe something:

```
class SomeComponent extends owl.Component {
  state = useState({ a: 0, b: 1 });
  otherState = { c: 2, d: 3 };
}
```
In that example, changing something in `otherState` will not rerender the component. But changing something in `state` will rerender the component.
