### ISSUE TITLE
doc components: feedback about Properties

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#342]
> It can be dynamically changed later by the parent, in some case.

Which cases? How? Why? It's either telling too little or too much.

> Note that props are owned by the parent, not by the component. As such, it should not ever be modified by the component!!

Then why allow it? Too hard to implement?

**Comment by ged-odoo** [comment]
the parent component can change the attributes given to the children component dynamically.

From the perspective of the children, all of these values are collected in the `props` object.  And anything inside that props object should be considered readonly (for the children component).
