### ISSUE TITLE
doc store: feedback about Semantics, coordination

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#345]
> in general, updates are not coordinated. This is not a problem for synchronous components, but if there are many asynchronous components, this could lead to a situation where some part of the UI is updated and other parts of the UI is not updated.

I'm not sure to understand the impact of this point, but it seems important. I would like to know more, and especially how it can be mitigated.

If I'm changing a state in the store, I would hope all components that use this state to be updated at the same time to avoid flickering and/or inconsistencies.

Of course, if the components themselves are async (is it possible, like doing an RPC during rendering?! seems like a bad idea), then obviously they might be unsync, but that seems like a design problem in the first place.

**Comment by seb-odoo** [comment]
> since the useStore function is called for each connected component, for each state update, it is important to make sure that these functions are as fast as possible.

Which functions? The `useStore` selector and equality?

When are they considered slow, and how to make them fast?

**Comment by ged-odoo** [comment]
"fixed" by removing support for store in owl 2
