### ISSUE TITLE
doc router typos

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#356]
> there are some steps that need~~s~~ to be done

**Comment by seb-odoo** [comment]
> A route need**s** to be defined as an object with the following keys:

**Comment by seb-odoo** [comment]
> the following guard checks if there is an authenticated user, and if it is not the case, redirect**s** to the sign in route

**Comment by seb-odoo** [comment]
> The Link component is a Owl component which render**s** as

**Comment by ged-odoo** [comment]
wont fix (owl 2 does not have the router anymore)

**Comment by mostafabarmshory** [comment]
Is there any simple way to support router in OWL2?
