### ISSUE TITLE
Owl playground demo is broken

### ISSUE THREAD

**Issue by Yenthe666** [odoo/owl#364]
Go to https://odoo.github.io/owl/playground/ and click run.. you'll get a SyntaxError right away:
![image](https://user-images.githubusercontent.com/6352350/67099622-978a1500-f1be-11e9-843e-0135a3548fa7.png)

**Comment by Yenthe666** [comment]
@aab-odoo & @seb-odoo would be neat to have this guy up again ;)

**Comment by ged-odoo** [comment]
argh, this is fixed by commit https://github.com/odoo/owl/commit/2b5783d9bd2d3a17b4a9fe79e65ceac484968778, but it is not deployed yet.  I'll update the playground right away

**Comment by ged-odoo** [comment]
@Yenthe666 it should be fixed now (but you may need to refresh with no cache).

**Comment by Yenthe666** [comment]
Thanks! 🎉 📯
