### ISSUE TITLE
namespacing of store actions

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#374]
As discussed, when having a "big" store, the action file quickly becomes very hard to maintain (currently past 4000 lines in our case).

I would like to split the actions in more logical blocks, but I'm not sure how to achieve that.

We mentioned the idea of simply splitting the action object in several files and merging the different parts together with `Object.assign`, but that means there could be conflicting names.

Hence the suggestion to namespace them somehow.

**Comment by ged-odoo** [comment]
```js
const messageStore = {
  name: 'message',
  actions: {
    create({state, dispatch, globalState}, params) {
        // globalState.channel
       dispatch('markRead', ...);
       dispatch('channel/create');
    },
    markRead(state, messageId) {},
  },
  state: {
     messages: {},
     lastMessage: null,
  }
};

const channelStore = {
  name: 'channel',
  actions: {
    create(...) {},
    close(state, channelId) {},
  },
  state: {
     channels: {},
  }
};

const store = new Store([messageStore, channelStore], env);
```

**Comment by ged-odoo** [comment]
fixed in owl 2 (by removing store)
