### ISSUE TITLE
props validation: add a way to define custom validator

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#375]
Use case: have a property that can take a specific number of pre-defined values.

Eg. 
- a string which can be either 'small', 'medium' or 'large'
- a number which can only be in a range (0...10)

**Comment by ged-odoo** [comment]
what about allowing components to define a validator themselves, as a predicate? So you can get all of these validations without adding more syntax to owl:

```js
static props = {
  abc: { validate: e => ['small', 'medium', 'large'].includes(e) },
  def: { type: Number, validate: n => 0 <= n && n <= 10 },
};
```

**Comment by seb-odoo** [comment]
Sure, that's even more flexible.
