### ISSUE TITLE
take default props into account when doing validation

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#379]
`props` defined as `areButtonsInline: Boolean,` (required)

`defaultProps` defined as `areButtonsInline: true,`

Declare the component in an xml, not specifying the `areButtonsInline` prop.

Error: `Missing props`

Expected: no error

**Comment by seb-odoo** [comment]
@ged-odoo The issue was fixed when instantiating a (root) component from the JS but not when instantiating a child component from a template.

**Comment by ged-odoo** [comment]
hmm, look at the commit: there is a test with a child component from a template.  Could you give me a way to reproduce your issue?

**Comment by ged-odoo** [comment]
https://github.com/odoo/owl/pull/385/commits/8bf2c7542ecd920598d128ff7e3fd96f99d2ec03

**Comment by seb-odoo** [comment]
This is strange, I can't reproduce the issue on my current computer, but it is because validation is actually not done at all.

The following example should fail because p is required, but I can't get it to crash on this owl version (supposedly built today): http://664907-master-mail-owl-2-seb-seb-172392-all.runbot25.odoo.com/web/static/lib/owl/owl.js

It does not contain the line ```ctx.addLine(`utils.validateProps(W${componentID}, props${componentID})`);``` that was removed, so it should be correct.

```js
(async () => {
owl.QWeb.dev = true;
const qweb = new owl.QWeb();
const env = { qweb: qweb };

class TestWidget extends owl.Component {}
TestWidget.props = {p: Boolean};
TestWidget.template = owl.tags.xml`<span><t t-if="props.p">hey</t></span>`;

class App extends owl.Component {}
App.template = owl.tags.xml`<div><TestWidget/></div>`;
App.components = { TestWidget };

const w = new App(env, {});
await w.mount(document.body);
console.log("done");
})();

```
What do I miss that makes this not log the error?

**Comment by seb-odoo** [comment]
PS: if I run that exact example on the dev console of the playground (that is not updated with the fix), I do get `Error: "Missing props 'p' (component 'TestWidget')"`

**Comment by seb-odoo** [comment]
Now that the playground has been updated, when I run the above code in the console, I do not get the validation error that should happen.
