### ISSUE TITLE
automatically add the component name as "class" name?

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#380]
For code/CSS clarity, easier xpathing, etc, it appears we took the convention in discuss to always add `class="o_ComponentName"` on the root element of all our components.

Since this is a rather repetitive and easily automatable task, I'm wondering if the framework shouldn't automatically take care of it? With an optional prefix specified in the environment (which would always be `o_` for us).

~~Then I'm wondering if we shouldn't also prefix by module name, which leads to the additional suggestion of being able to namespace components? I'll make a new issue for that one specifically.~~
Edit: it seems like we can "namespace" with `static components` definition and importing appropriate components which are encapsulated into different odoo modules.

**Comment by ged-odoo** [comment]
hmm, it if is done in JS, then it will not be available in xpaths?
