### ISSUE TITLE
Component: remove 'renderBeforeRemount' option?

### ISSUE THREAD

**Issue by Polymorphe57** [odoo/owl#381]

**Comment by aab-odoo** [comment]
We could remove argument `renderBeforeRemount` as we can easily detect that the state has changed when the component is not mounted.

**Comment by aab-odoo** [comment]
Apparently, the bug has been fixed meanwhile. Still have to decide if we want/can get rid of 'renderBeforeRemount' arg.

Also, DAM suggested to specify options in an option dict (even though there is only one for now).

**Comment by ged-odoo** [comment]
The best would be to remove it.  Maybe we should always rerender by default?  And then, whenever we encounter a performance issue, we try to see if we can solve it with other strategies.  It seems unsafe not to rerender actually.  For example, if in the meantime the user resized the window, then remounting the component without rerendering it would lead to wrong result.
