### ISSUE TITLE
Issue with t-esc in t-if

### ISSUE THREAD

**Issue by pro-odoo** [odoo/owl#389]
When using t-esc directive in a t-if directive, there is an issue with the generated code. It looks like a curly bracket is missing.

To reproduce, here are what I used in the playground:
```
const { Component, useState } = owl;

class App extends Component {
    state = useState({ name: 'World'});
}

const qweb = new owl.QWeb(TEMPLATES);
const app = new App({ qweb });
app.mount(document.body);
```
and 
```
<templates>
    <div t-name="App">
        <t t-if="true" t-esc="state.name"/>
    </div>
</templates>
```

**Comment by ged-odoo** [comment]
should be solved by https://github.com/odoo/owl/commit/be556a970e2093798eceaae4fc5498f1518cb171
