### ISSUE TITLE
Add params when not specified in the route

### ISSUE THREAD

**Issue by Goaman** [odoo/owl#400]
Currently, when navigating and passing params to a route that does not possess params in it's definition lose not defined params at some point.

```javascript
const ROUTES = [
    { name: 'FOO', path: '/foo/{{p1}}', component: FooComponent },
]

// few lines of code later ...

router.navigate({ to: 'FOO', params: { p1: 'param1', p2: 'param2' } });
```
That currently generate the url `mydomain.tld/foo/param1`
But could instead generate the url `mydomain.tld/foo/param1?p2=param2`

**Comment by ged-odoo** [comment]
What about this instead?

```js
router.navigate({ to: 'FOO', params: { p1: 'param1' }, query: {p2: 'param2 });
```
this would generate the url `mydomain.tld/foo/param1?p2=param2`

**Comment by ged-odoo** [comment]
"fixed" by removing support for the router in owl 2
