### ISSUE TITLE
display current commit of playground

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#405]
It would be nice if the playground was linked to an exact commit instead of a revision, in order to know which intermediate fixes are already applied/ready to be tested or not.

More simply, the playground should probably be linked to a git branch (master) and updated automatically.
Maybe a parallel version could co-exist for each revisions/tags (or alternate branches if some day bug fix has to be done for several versions?).

**Comment by ged-odoo** [comment]
You can always do `owl.__info__.hash` in the console to get the commit hash that was used to build owl. Is that not enough?

**Comment by ged-odoo** [comment]
I added a link to the commit in the console, so you can just click on it instead of having to type `owl.__info__.hash` and copy paste it somewhere else.

**Comment by seb-odoo** [comment]
I didn't know about `owl.__info__.hash`, probably this would have been enough, but I like the console log too.
