### ISSUE TITLE
observer: properly handle Map/WeakMap/Set/WeakSet

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#420]
dans "get" du proxy de "_observe", j'ai rajouté ça:

if (typeof targetValue === 'function') {
          return targetValue.bind(target);
        }

conseillé par ce lien: https://stackoverflow.com/questions/43236329/why-is-proxy-to-a-map-object-in-es2015-not-working

ça résoud mon bug

et pour moi ça a du sens parce que, ok, les fonctions ne sont pas proxifiées par "observe" parce que typeof !== 'object', certes, mais elles sont renvoyées débindées, donc le this est mauvais

d'où mon crash parce que c'est une Map et qu'au lieu de faire un comportement bizarre parce que this est faux, elle throw carrément une erreur (pas plus mal sinon j'aurais galéré pour voir ce bug)

David Monjoie (dmo) - 37 minutes ago 

alors je me doute que t'as pas envie de tester le type de la valeur dans le "get" alors que tu as déjà un check de type dans "observe", mais dans ce cas il faudra passer "target" à "observe" pour pouvoir le binder 😕

**Comment by sdegueldre** [comment]
Handled correctly in owl 2 reactivity
