### ISSUE TITLE
add scheduler on Component?

### ISSUE THREAD

**Issue by Polymorphe57** [odoo/owl#433]
This was apparently 'planned' but not present in alpha version
```xml
Component.scheduler = scheduler;

```

**Comment by aab-odoo** [comment]
@ged-odoo They need to be able to mock the requestAnimationFrame callback used in the scheduler for their tests... For now, they can't access it. Do you agree to expose it somewhere ? (e.g. on Component, as dam suggested)

**Comment by ged-odoo** [comment]
It feels like there is a better solution, but I cannot see it.  In the meantime, this one is very simple and can easily be changed later if we have a better idea. So yes
