### ISSUE TITLE
non-deterministic issue in owl context.test.ts 

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#480]
I just had a non-deterministic issue when running owl tests.
I'm running `context.test.ts` dozen of times because I'm trying to reproduce an issue that I have by creating a new test on it, but one time I had a totally unrelated test crashing on me.

I managed to reproduce this issue another time by doing a loop, but this happens less than 5% of the time so it is still pretty hard to get it.

```
npm run test tests/context.test.ts 

> owl-framework@1.0.0-alpha3 test /home/odoo/repo/owl
> jest "tests/context.test.ts"

 FAIL  tests/context.test.ts
  ● Context › two async components on two levels are updated in parallel

    expect(received).toBe(expected) // Object.is equality

    Expected: "<div><span><p>321</p></span><div><span><p>321</p></span><span><p>321</p></span></div></div>"
    Received: "<div><span><p>321</p></span><div><span><p>123</p></span><span><p>123</p></span></div></div>"

      153 |     await nextTick();
      154 |     expect(steps).toEqual(["render", "render", "render"]);
    > 155 |     expect(fixture.innerHTML).toBe(
          |                               ^
      156 |       "<div><span><p>321</p></span><div><span><p>321</p></span><span><p>321</p></span></div></div>"
      157 |     );
      158 |   });

      at Object.test (tests/context.test.ts:155:31)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 10 passed, 11 total
Snapshots:   0 total
Time:        1.098s

```

**Comment by seb-odoo** [comment]
Still getting it on latest revision. I had to run it 70 times before getting it, and then I got it 2 other times quickly after.

**Comment by ged-odoo** [comment]
yep, it is a subtle issue with promises micro/macro task queues. The code is not wrong, but the test assumed that we had a guarantee that we cannot really be sure of. Should be closed soon
