### ISSUE TITLE
"Cannot set property 'sibling' of null"

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#483]
I'm getting this error on runbot but not locally. Since it's a qunit I'm not even getting a proper traceback.

I will investigate more if needed, unless you immediately see a case where `previousSibling` would be `null` when you assign `sibling` to it?

**Comment by ged-odoo** [comment]
do you have components that implement the `shouldUpdate` method?

**Comment by aab-odoo** [comment]
Could you provide more information about the scenario? At least a link to your test :-)

**Comment by seb-odoo** [comment]
I will investigate properly today and let you know.

**Comment by seb-odoo** [comment]
Just for reference, but you don't need to check it, example of failing runbot http://runbot.odoo.com/runbot/build/695231

I don't know what is `shouldUpdate` and we are not using it.
