### ISSUE TITLE
event handler of parent not called when triggering event from children in some situations

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#520]
It seems (without guarantee) to be related to nested components, where the child is triggering the event, and the parent was initially mounted, then destroyed, and recreated again.

**Comment by seb-odoo** [comment]
Also note that it is definitely an issue related to "time" as waiting a tick previously in the program can lead to the issue not appearing, and waiting differently could also lead to errors later in the program.

**Comment by seb-odoo** [comment]
I have cleaned and improved the test log a bit more, and it appears that the event listener that is not called in practice is still added before the click, when the new "preview list" is mounted.

But the low level handler itself that is created as string is not called according to the log I added in it.

Could it be that the child is not properly triggering/dispatching the event instead?

**Comment by seb-odoo** [comment]
Forget what I said on the last message, I wasn't checking the correct event.

I now confirm that the even is trigger properly, but that the parent didn't register the listener (so basically, back to the original ideal...).

**Comment by seb-odoo** [comment]
Result of my investigation so far:

good child:
- rendering template
- end of prepare and render (add listener to vnode.data.hook)
- actual add listener to dom
- mounted

bad child:
- rendering template
- mounted
- end of prepare and render (add listener to vnode.data.hook)
- (listener never added to dom)

**Comment by seb-odoo** [comment]
In the bad call it goes into __notifyComponents which does a scheduler flush immediately, before the promise then doing the listener stuff is executed.

**Comment by ged-odoo** [comment]
Keep us updated!  It's like a police tv show. I want to know the culprit...
