### ISSUE TITLE
don't use a value for t-else

### ISSUE THREAD

**Issue by amigrave** [odoo/owl#564]
Seems there are a lot of examples in the documentation which use a value for `t-else`, eg:
```html
<ul t-else="1">
```

This nonsense has started in qweb templates and people just copy/pasted it without thinking.
`t-else` attributes should not have a content and if the official documentation does it, the bleeding will continue.

If you absolutely want to force branching directives to have a value then you can still drop the `t-else` directive altogether and use `t-elif="true"` or `t-elif="1"` instead :)

**Comment by ged-odoo** [comment]
No value is not xml valid. I guess that you mean, just an empty string?
```xml
<ul t-else="">
```

Looks good to me.  Also, probably the same should be done for `t-debug`.

**Comment by amigrave** [comment]
yeps, this is what I meant
