### ISSUE TITLE
useRef hook returns array if multiple t-ref="same_name"

### ISSUE THREAD

**Issue by mcm-odoo** [odoo/owl#600]
When doing this:
```xml
<t t-foreach="iterable" t-as="iter" t-key="iter">
  <div t-ref="myRef">...</div>
</t>
```
useRef will return the last div in the iteration

It could be great if we can have all the divs
```js
class Comp extends owl.Component {
  constructor() {
    super(...arguments);
    this.myRefs = useRef('myRef');  // return an array with all divs from t-foreach
    this.myFirstRef = useRef('myRef', 0);
    this.myLastRef = useRef('myRef', -1);
  }
}
```

should not be only for t-foreach but t-foreach is a nice example
```xml
<div t-ref="myRef">A</div>
<!-- further in the xml -->
<div t-ref="myRef">B</div>
```

> To know if the ref is a simple element or an array we can define a convention for the name like `t-ref="simple"` for a simple element and `t-ref="[multiple]"` or `t-ref="multiple[]"` for array

**Comment by ged-odoo** [comment]
what about simply using string interpolation?

```xml
<t t-foreach="iterable" t-as="iter" t-key="iter">
  <div t-ref="myRef_{{iter}}">...</div>
</t>
```

it should work, and solve your issue without adding additional syntax

**Comment by mcm-odoo** [comment]
This was just a suggestion and the convention is not mandatory

In your case we will do
```js
class Comp extends owl.Component {
  constructor() {
    super(...arguments);
    this.myRefs = [];
    for (let i = 0; i < count; i++) {
      this.myRefs.push(useRef('myRef_' + i));
    }
  }
}
```
I'm ok with this code but what if we don't know the count of refs?
if we loop on a generator function?
