### ISSUE TITLE
feature request: async postMounted lifecycle hook

### ISSUE THREAD

**Issue by caburj** [odoo/owl#634]
The following pattern starts to emerge while migrating pos to owl:

>After a component is mounted (displayed), a task needs to be run automatically. We don't care if this task is done immediately or not, but once it's done we are still interested of its return (or error if it threw one).

I can still accomplish this by calling the async task inside `mounted` like so:

```js
constructor() {
  super(...arguments);
  useListener('comp-error', this.catchError);
}

mounted() {
  ...
  this.aPostMountedTask();
}

async aPostMountedTask() {
  try {
    this.delayedData = await this.rpc(...);
  } catch (error) {
    this.trigger('comp-error', { error });  
  }
}

catchError(error) {
  console.error(error);
}
```

I have no problem with the use of `trigger('comp-error'...)` to catch the error. However, the problem with this approach occurs when `postMounted` has a blocking function. As an example in pos, I am calling `window.print()` which blocks the call stack. Since the `mounted` call is only done after a requestAnimationFrame tick, the component is not displayed in the screen (even though the component is there when we investigate the dom elements).

I think we can do better if we introduce a new async lifecyle hook - `postMounted`. Its role is to run after the component is displayed in the screen (after mounted). Additionally, the component should be able to listen the thrown error - basically, `catchError` (or maybe a different one `catchPostMountedError`) should be able to catch the error thrown by `postMounted` call. In that case, we will only need to declare like so to accomplish the pattern I described above:

```js
async postMounted() {
    this.delayedData = await this.rpc(...);
}

catchError(error) {
  console.error(error);
}
```

I believe this can be accomplished by wrapping the postMounted call inside a new requestAnimationFrame after component.__callMounted(). And the error can be thrown by triggering an event which runs the catchError callback.

```js
  component.__callMounted();
  const compPostMounted = component;
  raf(async () => {
    try {
      await compPostMounted.postMounted();
    } catch (error) {
      // we declare useListener('error') in the Component.
      compPostMounted.trigger('error', error)
    }
  });
```

**Comment by ged-odoo** [comment]
Is it not enough to just do this in your `mounted` lifecycle method?
```js
mounted() {
  setTimeout(() => this.aPostMountedTask());
}
```

Also, a new lifecycle hook is very costly, from the perspective of the framework, so I will need a really good use case to consider it!

**Comment by caburj** [comment]
My bad for not considering the cost of introducing a new hook. And besides, the use of setTimeout is actually enough. :) I'll close this issue.
