### ISSUE TITLE
issue: useRef not working on top level Dialog

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#638]
For example this template
```xml
    <t t-name="mail.component.ModerationBanDialog" owl="1">
        <Dialog title="'Confirmation'" size="'medium'" t-ref="dialog">
        </Dialog>
    </t>
```
and this `useRef`:
```js
this.dialog = useRef('dialog');
```
But `this.dialog.comp` is `null`. I would expect it to be the dialog component.

This works as expected if I add a dummy `div` around the `Dialog` in the template.

**Comment by msh-odoo** [comment]
@seb-odoo I faced same issue and end up with wrapping template in extra div

**Comment by ged-odoo** [comment]
@seb-odoo  Can you tell me if `this.dialog.el` is properly set in this situation?

@msh-odoo  Whenever you encounter issues with Owl, open an issue on this repo! We can make Owl better!

**Comment by seb-odoo** [comment]
this.dialog.el -> null
this.dialog.comp -> null
this.__owl__.refs -> {}
