### ISSUE TITLE
[transition] TypeError: node is null

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#641]
I'm not exactly sure how to reproduce, I think with quick successive renders including transitions.

Version on current Odoo master.

```
TypeError: node is null owl.js:708:9
    removeChild http://127.0.0.1:8069/web/static/lib/owl/owl.js:708
    rmCb http://127.0.0.1:8069/web/static/lib/owl/owl.js:430
    finalize http://127.0.0.1:8069/web/static/lib/owl/owl.js:2512
    whenTransitionEnd http://127.0.0.1:8069/web/static/lib/owl/owl.js:2545
    transitionRemove http://127.0.0.1:8069/web/static/lib/owl/owl.js:2517
```

**Comment by ged-odoo** [comment]
maybe the same as #637

**Comment by seb-odoo** [comment]
Looks the same to me indeed.

**Comment by ged-odoo** [comment]
found a way to reproduce it fairly easily:
1. go on playground
2. open animation example
3. inspect "Toggle square" button and bind it in the console: `b = $0;`
4. add this in the console: `setInterval(() => b.click(), 0)`

It now crashes usually, if not, by clicking elsewhere to trigger rerenders.
