### ISSUE TITLE
add support for event capture on t-on

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#650]

**Comment by aab-odoo** [comment]
@caburj fyi

**Comment by caburj** [comment]
I was tinkering on the code and I somehow found a way to introduce this `options` like so -- `t-on-event.capture.once="eventHandler"` -- on Component, but I got stuck on making it work on basic Html element. Then I stumble upon this issue in snabbdom: https://github.com/snabbdom/snabbdom/issues/365

I think snabbdom is the bottleneck here on implementing this feature.
