### ISSUE TITLE
odoo owl

### ISSUE THREAD

**Issue by ghost** [odoo/owl#678]
hi, 
I'm just experimenting with the owl framework. 
What I'm currently missing in the docs is an example app using the router, this would be really helpful to me. Can somebody show me how to use it ? 
Regards
Rolf

**Comment by ged-odoo** [comment]
This is an excellent suggestion. You are right, the documentation is lacking in that regard.

Sorry to take so long to answer, life is a little bit difficult for now. I'll try to work on this as soon as i can

**Comment by bobslee** [comment]
@ged-odoo Maybe you could give a suggestion how to implement routing?

**Comment by bobslee** [comment]
I just found the Router documentation https://github.com/odoo/owl/blob/master/doc/reference/router.md
@ged-odoo Is it somehow usable and stable in this regard?

**Comment by sdegueldre** [comment]
Router no longer exists in owl 2
