### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by alfadil** [odoo/owl#679]
hi
I think this library would be a great step forward for odoo, and I want to contribute and be a part of it's creation, so I was wondering how to contribute to this library.

**Comment by ged-odoo** [comment]
Ooh, that would be great! Thank you for your help. Sorry to take that much time to answer, with this coronavirus pandemic, life is a little bit crazy for now.

Do you have any specific idea/things that you want/prefer to improve?

Obviously, Owl is kind of technical/low level, so it may be slightly difficult to get into. There are multiple ways to help:
- write documentation
- write tutorials or how tos for specific problems
- solve simple issues, such as #683 
- work on some other more difficult issues

Tell me more, and I will try to help/guide you a little bit if you want

**Comment by alfadil** [comment]
thanks for your guidance ,I'm to fix some of issues , 
And I hope I can add some work to this framework .
