### ISSUE TITLE
Component constructor should accept env (and not parent?)

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#688]
Conceptually `env` should always be given by the code instantiating the component.

The issue is manifesting especially for tests where there is:
- the global env (of the window running the tests),
- the test specific env (one env for each test).

To properly handle this case in tests we must do the following, on each test:
```js
Component.env = testEnv;
new Component(null, props); // unnecessary null parent
// delete just to be safe, ideally should even restore the env that was set before line 1...
delete Component.env;
```
To avoid issues I think currently all instantiations of a root component in business code should always write the `env` on the class again before every `new`.

The signature of the constructor with the parent as param is a technical detail that is never used outside of the framework itself, and the usual signature (as root component) currently requires a `null` param and extra code.

Ideally this should be it:
```js
new Component(testEnv, props); 
```

**Comment by ged-odoo** [comment]
agreed. But I would go even further (and I plan to do it in owl 2): it is also slightly awkward to have a difference between the root component (which is instantiated by the developer) and every other components (which are managed by owl). After looking at how I would support functional components and looking at other frameworks, I believe that the correct API is this: a separate mount method, that take the class, not an instance. Something like this:

```js
mount(MyComponent, {target: document.body, env: myEnv});
```

**Comment by seb-odoo** [comment]
How do you receive the instance then? It contains public attributes and methods that can be useful.

**Comment by ged-odoo** [comment]
I should check my preliminary work, but I think that the `mount` method returns a `Promise<Component>`, so you can just wait on it. 

But I am interested in your use case. Because to me, it looks like a red flag to use the instance (at least in the application. it's ok in the tests)

**Comment by seb-odoo** [comment]
As an example: everything in `owl_compatibility`, especially updating props.

More generally, if the power is given to mount as specific component, it should at least be possible to unmount it too (and destroy when we are done with it).

(Also rerender, to be able to do like useStore but through manual means, though that one can probably be "bound" from inside the component itself just like useStore is.)
