### ISSUE TITLE
subTemplates are lost after creating a new qweb instance

### ISSUE THREAD

**Issue by pro-odoo** [odoo/owl#701]
With the given code on the playground, one of the two templates are not rendered, with an error `cannot read property call on undefined`, at the following line: `this.subTemplates['__template__5'].call(`.

`this.subTemplates` is correct the first time (it contains `__template__5`), but the second time, `this.subTemplates` is empty. 

The issue was spotted when we tried to write test cases in Odoo for spreadsheet:
We created two different tests, in each one we created a new test environment (which instantiate a new QWeb instance). Each test works alone, but if we run the two, the second fails with the same error.

Playground code:
``` js
const { Component, useState } = owl;
const { xml } = owl.tags;

const temp = xml`<div>test</div>`;

class Greeter extends Component {
    static template = xml`<div><t t-call="${temp}"/></div>`;
}

const app = new Greeter();
Greeter.env.qweb = new owl.QWeb()
const app2 = new Greeter();

app.mount(document.body);
app2.mount(document.body);
```

**Comment by ged-odoo** [comment]
this one is actually very annoying. I do not see a good way to solve it. I think we made a mistake with owl, influenced by the way QWeb and Odoo works: making the user manage qweb instances.  In my early design for owl 2.0, this is no longer the case

**Comment by ged-odoo** [comment]
ok, found a way to solve this
