### ISSUE TITLE
Owl and PWAs

### ISSUE THREAD

**Issue by j209** [odoo/owl#704]
Hi
Can owl implement service worker for [pwa](https://developers.google.com/web/progressive-web-apps/)?
and if the answer is no is there any plan ?

**Comment by ged-odoo** [comment]
Hello @j209 

Owl is trying to be a small rendering engine/component framework, with a lot of nice features, but most of them specific to the UI part of the application.

As far as I know, service workers are mostly concerned with the networking aspect, so I would say that Owl will not help you on that part. 

However, in the future, Odoo will likely implement PWA in some part of its codebase.  If we find that we need support from Owl (at the framework level), we will do it.  Or if someone else can show us a good usecase, and what it would need from owl, it could also be done.

Note that we also investigated web workers to offload part of the rendering from owl to another thread, but this is more an internal detail of implementation.
