### ISSUE TITLE
Suggestion: Component for library binding

### ISSUE THREAD

**Issue by mcm-odoo** [odoo/owl#705]
> It's a bit like a draft, I think about this since a while and I wanted to shared it.

I'm working on the conversion of map and calendar views and these views use libraries (Leaflet and Fullcalendar).
What I do is:
1. I create my template with a `t-ref` somewhere and in `Component.mounted()` I attach **manually** the map/calendar.
2. To make the views dynamic I change some elements in `Component.patched()`. For example, the markers in the map view are re-rendered **manually** at every patches.
3. When the component is destroyed, I also have to destroy everything I added.

What I propose is a component that could ease libraries bindings.
example of template with "`BindingComponent`"
```xml
<div>
  <header>A header for my map</header>
  <LeafletMap>
    <t t-foreach="markers" t-as="marker" t-key="marker.id">
      <LeafletMapMarker location="[marker.location.x, marker.location.y]"/>
    </t>
  </LeafletMap>
</div>
```
As we can see it's quite clear: We want leaflet to create a map and this map has markers.

I don't think it will be used only by Odoo but one day maybe someone would work on an owl binding for Fullcalendar or an another lib and this could help them.

**Comment by ged-odoo** [comment]
i'll close this issue, since it seems a little too vague, and owl 2 is different. If you want to reopen it, @mcm-odoo please do. in that case, it would be interesting to have a more precise example of what owl should do
