### ISSUE TITLE
Plans on merging OWL with core

### ISSUE THREAD

**Issue by kirtangajjar** [odoo/owl#707]
This project looks really great but I wasn't able to find if there are any plans on merging it with odoo core. If yes, is there any ETA?

Super excited for this. Good work guys :smiley: :+1:

**Comment by ged-odoo** [comment]
Thanks :)

Merging with the odoo web client? No, we expect to keep developing Owl in this repository.  But Owl is used (just like a library) in the odoo web client. It is available right now in master, and all current and future JS development will use it.  

We will simply keep the Owl code in the web client up to date, just like a normal library.

**Comment by kirtangajjar** [comment]
That's great to hear. So does that mean going forward, existing plugin's JS functionality will need to be ported to owl i.e. from v14 or 15?

**Comment by kirtangajjar** [comment]
I think so, anyways thanks for the reply.
