### ISSUE TITLE
renderToString always escapes content

### ISSUE THREAD

**Issue by xdu-odoo** [odoo/owl#708]
Hey guys ! I think I found something that could be a bug : `renderToString` seems to always escape the content of the used template.

Whether it should not (in the playground below, the `<t t-raw="state.name"/>` was expected to show the right content, `&làbas`), whether the use of this function should be restricted somehow as the use case here is not possible.

Basically the idea was to use an owl template to render the label of an item to be used in autocomplete source function which could be useful I think (btw we did it differently thus).

```js
const { Component, useState } = owl;
const { renderToString } = owl.Component.env.qweb;

// Main root component
class App extends Component {
    constructor() {
        super(...arguments);
        this.state = useState({
            name: owl.Component.env.qweb.renderToString('testtemplate', {myVal: '&làbas !'})
        });
        
    }
}

// Application setup
const app = new App();
app.mount(document.body);
```

```xml
<templates>
  <div t-name="App">
    <ul>
      <li>
        <strong>esc</strong>: <t t-esc="state.name"/>
      </li>
      <li>
        <strong>raw</strong>: <t t-raw="state.name"/>
      </li>
    </ul>
  </div>
  
  <t t-name="testtemplate">
        <strong>This is myVal : <em><t t-raw="myVal"/></em></strong>
    </t>
</templates>

```

**Comment by xdu-odoo** [comment]
FYI @seb-odoo

**Comment by msh-odoo** [comment]
@ged-odoo @aab-odoo I have task where I was getting string "Research & Development" as "Research &amp; Development" in UI, I found issue was because of renderToString and it is produced after commit: b2f12a111524f37348b142ac248813f9cb25ca2e

**Comment by msh-odoo** [comment]
@ged-odoo Issue is coming since commit: https://github.com/odoo/owl/commit/b2f12a111524f37348b142ac248813f9cb25ca2e

Do we really need to escape ```node.textContent``` I guess if you render something like below then it will give escaped string, don't you think?

```qweb.addTemplate("test", `<span><t t-esc="var"/></span>`);
renderToString(qweb, "test", { var: "<ok>" })```

this will result: ```<span>&lt;ok&gt;</span>```

as ```renderToString``` return ```outerHTML```, Isn't it expected result?

cc: @aab-odoo @seb-odoo
