### ISSUE TITLE
[BUG] Misuses of 't-key' are silent and prevent template rendering

### ISSUE THREAD

**Issue by Arcasias** [odoo/owl#711]
**JS**

```js
class Child extends owl.Component {
    static template = owl.tags.xml`
        <div t-esc="props.text"/>
    `
}

class App extends owl.Component {
    state = owl.useState([
        { text: "a" },
        { text: "b" },
    ]);
    static components = { Child };
    static template = owl.tags.xml`
        <div>
            <Child t-foreach="state" t-as="x" t-key="x.id" text="x.text"/>
        </div>`;
}

const app = new App();
app.mount(document.body);
```

**Problem**
Template is not rendered due to the `t-key` directive returning `undefined` twice, although the console displays no error or warning.
This problem only seems to occur when using child components.

**Comment by SimonGenin** [comment]
- Fails only on child components.
- Should not fail: everywhere else, a duplicate key won't prevent rendering. Elements order should just be a bit of a mess sometimes.
- We could still give warning if duplicate key is detected.

**Comment by ged-odoo** [comment]
fixed in owl 2
