### ISSUE TITLE
t-call with component in t-foreach

### ISSUE THREAD

**Issue by msh-odoo** [odoo/owl#715]
I have following scenario where component inside t-call uses variables from t-foreach
```XML
<t t-name="sub">
  <t t-log="employee.name"/>  <!-- will be logged -->
  <Popover> <!-- Consider Popover is portal component -->
    <t t-log="employee.name"/> <!-- here last employee name is logged -->
    <span t-att-data-emp-name="employee.name">Click Here</span> <!-- here data will be last employee name -->
  </Popover>
</t>
<div t-name="App">
  <t t-foreach="employees" t-as="employee" t-key="employee.id">
    <t t-call="sub"/>
  </t>
</div>
```

Here span inside popover will have last employee name in data, it seems if t-call has component then foreach don't wait for component to render.

BTW, I did same thing where I make ```sub``` as Component instead call it using ```t-call```, say for example if I have following code then it works fine, I think it should also work in case of ```t-call``` example given above.

```XML
<t t-name="sub">
  <t t-log="props.employee.name"/>  <!-- will be logged -->
  <Popover> <!-- Consider Popover is portal component -->
    <t t-log="props.employee.name"/> <!-- here last employee name is logged -->
    <span t-att-data-emp-name="props.employee.name">Click Here</span> <!-- here data will be last employee name -->
  </Popover>
</t>
<div t-name="App">
  <t t-foreach="employees" t-as="employee" t-key="employee.id">
    <sub employee="employee"/>
  </t>
</div>
```

**Comment by ged-odoo** [comment]
Hey @msh-odoo 
Sorry to come this late to this issue.  I just tried reproducing the problem, but it seems fine to me. Here is a slightly simplified version that you can use in the playground:

```js
// In this example, we show how components can be defined and created.
const { Component, useState } = owl;

class Child extends owl.Component {
    static template = owl.tags.xml`<div><t t-slot="default"/></div>`;
}

class App extends owl.Component {
    static components = { Child };

    employees = [ {id: 1, name: 'a'}, {id: 2, name: 'b'}];
}

const app = new App();
app.mount(document.body);
```

```xml
<templates>
<t t-name="sub">
  <Child>
    <span t-esc="employee.name"/>
  </Child>
</t>
<div t-name="App">
  <t t-foreach="employees" t-as="employee" t-key="employee.id">
    <t t-call="sub"/>
  </t>
</div>
</templates>
```
It displays `a` and `b`, which is what we expect. Can you tell me if the problem has been solved, or if not, how to reproduce it?  (it may have been fixed in some newer owl version)

**Comment by SimonGenin** [comment]
@msh-odoo I'm closing the issue, unless you have a counter argument ? Maybe the bug only appears with portals ? Provide full code to be tested in the playground if your case is complicated.
