### ISSUE TITLE
t-foreach not supporting custom iterators

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#720]
Due to
```ts
    ctx.addLine(`_${keysID} = Object.keys(_${arrayID});`);
    ctx.addLine(`_${valuesID} = Object.values(_${arrayID});`);
```
`t-foreach` is not supporting custom iterators. For example, but not limited to, using native `Set`.

Suggestion: replace the above lines by
```ts
ctx.addLine(`_${arrayID} = [..._${arrayID}];`);
```
This works for Set (or any value where `typeof _${arrayID}[Symbol.iterator] === 'function'`) but probably not for objects though. 
Alternative would be to use
```ts
`_${arrayID}.keys()`
`_${arrayID}.values()`
```
or
```ts
`_${arrayID}.constructor.keys(_${arrayID})`
`_${arrayID}.constructor.values(_${arrayID})`
```
for the objects that do have them.

**Comment by alexkuhn** [comment]
I disagree with not supporting `Set` or `Map` with `t-foreach`:
The declarative nature of this directive suggests it to work with any iterable.

I'm not saying the workaround to prefixing expression with `...` is a big deal, but I'm disappointed that `t-foreach` supporting `Set` and `Map` _ is considered as "a little too much in term of code/magic"_.
Actually, having `t-foreach` to work on just a few iterables seems counter-intuitive.

Are there any (significant) performance issues by supporting all iterables?
If not, I don't see why `t-foreach` should be restricted to arrays (and objects).

**Comment by ged-odoo** [comment]
No, the directive is documented to work with arrays and objects. There is nothing non declarative about that. Also, using '...' operator is not a workaround. It is a standard JS operator to convert iterables to an array. which is exactly what you want in this case.  Thinking about it this way, it looks like you want to replace some of the expressive power of the language by a directive.

Owl is supposed to be a "low level of abstraction" UI layer. Not solve every problems.  In this case, I believe that there is not really much value added by this proposition. If there is not a clear benefit, and especially in this case where standard ES features work perfectly, I believe that we should err to the side of not doing it.

**Comment by seb-odoo** [comment]
Converting Set or Map to a list with `...` has a cost (CPU and probably also memory). This cost might be higher than the cost of supporting iterating them directly. I have no value to back this up right now, but something to keep in mind and maybe investigate further.

It has also a cost in terms of code clarity and maintenance. In standard JS code, `for ... of` loop can take either, which is very convenient. `t-foreach="[...mySet]"` doesn't look good in the template, anyone wanting to iterate a set/map will naturally try without spread and it will fail (pit of success), and it prevents from easily refactoring code when there is a need to interchange a variable from being a set/array (I know other methods on those elements are not interchangeable either but this just adds on top of it).

I don't understand the argument about "low level", Set/Map are just as "low level" as Array to me, and only business needs should dictate which one to use (Map when keys are "complex", Set to guarantee uniqueness and/or have O(1) "has", ...). I don't like that the framework is forcing us to use Array to iterate when it's not a proper fit for our data.
