### ISSUE TITLE
Suggestion: new directive t-tag

### ISSUE THREAD

**Issue by mcm-odoo** [odoo/owl#721]
This directive could be useful when we have a conditionnal tag

e.g.
```xml
<ol t-if="isOrdered">
  I do something
</ol>
<ul t-else="">
  I do the exact same thing as above
</ul>
```

With t-tag we could do
```xml
<t t-tag="isOrdered ? 'ol' : 'ul'">...</t>
```

_The exemple is a real case I encountered_

**Comment by ged-odoo** [comment]
I kind of like this...  There are other ways to solve the issue, but not as elegant:
1. make another template and call it with the common content inside (so, will be used with a `t-raw="0"`)
2. define a variable with `t-esc` with the common content, if possible
3. keep the duplication

Also, we have the `t-component` directive, so it makes sense to have this for tags...

**Comment by ged-odoo** [comment]
Note: dam has a need for something that look like this:
```xml
<a t-if="item.href" t-att-ref="item.href">
  <t t-esc="item.description"/>
</a>
<t t-else="">
  <t t-esc="item.description"/>
</t>
```
This could be done with `t-tag` as well, by taking the convention that if `t-tag` returns an empty string, then there is just no node at all

**Comment by brboi** [comment]
@ged-odoo it is not clear of what would happen to the `t-att-href` directive in the case the `t-tag` returns an empty string.

Some snippets:

```xml
<t t-tag="item.href ? 'a' : ''" t-att-href="item.href">
  <t t-esc="item.description"/>
</t>
```

Or in one line:
```xml
<t t-tag="item.href ? 'a' : ''" t-att-href="item.href" t-esc="item.description"/>
```

Without `t-tag`:
```xml
<a t-if="item.href" t-att-href="item.href" t-esc="item.description"/>
<t t-else="" t-esc="item.description"/>
```

I personally prefer the third snippet.
I think that `t-tag` must definitely be implemented, but my point is I am not sure we should take your mentioned convention about this directive returning an empty string. IMHO, `t-tag` should expect a non-empty tag.

**Comment by brboi** [comment]
Just another (probably bad) idea: `t-tag-attributes`
```xml
<t t-tag="item.href ? 'a' : ''" t-tag-attributes="{ a: { href: item.href }}" t-esc="item.description"/>
```
