### ISSUE TITLE
Support template strings?

### ISSUE THREAD

**Issue by mcm-odoo** [odoo/owl#746]
Writting a simple template string in xml throws an error: Unexpected identifier

```xml
<t t-esc="`Hello, World!`"/>
```

**Comment by dhp-odoo** [comment]
@mcm-odoo 
you can use <div t-esc="`Hello, World!`"/> instead

**Comment by mcm-odoo** [comment]
No, you cannot
`<span t-esc="Hello, World!"/>` will generate an internal code line `let _N = scope['Hello'], scope['World']!;`
and will crash when executing it

Correct form is
```xml
<span t-esc="'Hello, World!'"/>
```
I asked for template strings ` `` ` because with this type of string you can do something like
```js
const username = 'MCM';
console.log(`Hello ${usename}!`); // logs "Hello MCM!"
```
