### ISSUE TITLE
t-raw display comment as text

### ISSUE THREAD

**Issue by ndeodoo** [odoo/owl#761]
```JS
const { Component } = owl;
class App extends Component {
    get content() {
        return `<p>Hello</p><!-- my friends -->`;
    }
}
const app = new App();
app.mount(document.body);
```

```XML
<div t-name="App">
  <t t-raw="content"/>
</div>
```

Expected: Hello
Result: Hello my friends

**Comment by ged-odoo** [comment]
nice find. this one is probably a stupid omission in the htmltovdom function. should be easy to fix

**Comment by ndeodoo** [comment]
@ged-odoo Thank you, I found it thanks to the help of aku. Actually, the original error is that any comment in a mail template is displayed in the chatter (issue from the pad). If you can keep me up to date with this issue it would be really nice :)

**Comment by ged-odoo** [comment]
@ndeodoo oh, so it's kind of urgent then. I'll work on it as soon as I can. If all goes well, should get a fix this afternoon

**Comment by ndeodoo** [comment]
@ged-odoo Perfect, thank you for your help :)

**Comment by rrahir** [comment]
@ged-odoo If it can help, I think that  in  htmltoVDOM
```
        for (let child of doc.body.childNodes) {
            result.push(htmlToVNode(child));
        }
```
should become something like
```
        for (let child of doc.body.childNodes) {
            if (!child instanceof Comment){
               result.push(htmlToVNode(child));
            }
        }
```
Should do the trick ^^

**Comment by ndeodoo** [comment]
Actually, @ged-odoo , @rrahir it  seems that the example above works: 

```
    function htmlToVNode(node) {
        if (!(node instanceof Element)) {
            return { text: node.textContent };
        }
        const attrs = {};
        for (let attr of node.attributes) {
            attrs[attr.name] = attr.textContent;
        }
        const children = [];
        for (let c of node.childNodes) {
            if (!(c instanceof Comment)){
                children.push(htmlToVNode(c));
            }
        }
        const vnode = h(node.tagName, { attrs }, children);
        if (vnode.sel === "svg") {
            addNS(vnode.data, vnode.children, vnode.sel);
        }
        return vnode;
    }

```

**Comment by ndeodoo** [comment]
@ged-odoo Do you want me to do a PR with this solution or do you prefer to handle it yourself (I may miss some other corner case, I would understand if you prefer handle this yourself )?

**Comment by ged-odoo** [comment]
@ndeodoo oh i did not see your message... just made a fix

**Comment by ndeodoo** [comment]
@ged-odoo No problem, thank you for the fix :)
