### ISSUE TITLE
add support for render functions

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#778]
Some extremely dynamic components are difficult to make in a template. For example, imagine some kind of NoteBook components, that display a tabbed menubar and a current page. Here is something that we would like to write:

```xml
<NoteBook>
  <Page title="'Some Title'">
    content1
  </Page>
  <Page title="'Some other Title'">
    content2
  </Page>
</NoteBook>
```

This is currently not possible, because the notebook component has no access to the (unprocessed) content of the default slot (or any other slot, for that matter).

What we would like to do is then something like this:
```js
class NoteBook extends Component {
  render(children) {
    // here, children = [{tag: "Page", attrs: {title: "Some Title"}, children: []}, {...}];
    const current = ...;
    return [
      this.renderTabBar(children),
      Page.render(current),
    ];
  }
}
```
Lots of questions arise as to how this would look like...  Very interesting research project

**Comment by sdegueldre** [comment]
The notebook issue has been solved by making slots more powerful. Having access to render functions may still be useful in a different capacity but I'm closing this for now, we'll create new issues if a more use case comes up.
