### ISSUE TITLE
No way to modify (include) owl component classes

### ISSUE THREAD

**Issue by LuisMalave2001** [odoo/owl#794]
I had to use Object.setProperty to simulate the "include" method, I know this is a Javascript problem, but, It would be helpful if we have a easy way to add methods, extend constructor and use hooks to a javascript Component class in A module from B module

**Comment by rauletepaz** [comment]
Hi,

     I have the same problem. I've found a work around but I'm not totally satisfied despite it works. I fear that if other module want to change the same component only one version will be alive.

```
odoo.define('mail_message_select/static/src/js/mail_message_select.js', function (require) {
'use strict';

const {Context} = owl;
const {useContext} = owl.hooks;
const DiscussWidget = require('mail/static/src/widgets/discuss/discuss.js'); 
const MessageList = require('mail/static/src/components/message_list/message_list.js'); 
const oldMessage = require('mail/static/src/components/message/message.js'); 

DiscussWidget.include({
    willStart: async function () {
        await this._super(...arguments);
        this.env.selectedMessage = new Context({localId: undefined});
    },
});

class newMessage extends oldMessage {
    constructor(parent, props) {
        super(parent, props);
        this.selectedMessage = useContext(parent.env.selectedMessage);
        /* Here you can add useState, useRef... */
    }

    _onClick(ev) {
        super._onClick(ev);
        this.env.selectedMessage.state.localId = this.props.messageLocalId;
    }

	get isSelectedMessage () {
		return (this.env.selectedMessage.state.localId === this.props.messageLocalId);
	}
};

MessageList.components.Message = newMessage; // Apply the new inherited component to parent!!!!

});
```

**Comment by ged-odoo** [comment]
I agree. The plan is now:

1. add a `setup` lifecycle method called by the constructor, so it can easily be extended by other methods
2. provide (in odoo) the following patch utility method:

```js
function patch(C, mixin) {
    for (let k in mixin) {
        const prevVal = C.prototype[k];
        const newVal = mixin[k]
        if (typeof newVal === "function") {
            if (prevVal) {
                C.prototype[k] = function(...args) {
                    this._super = prevVal.bind(this);
                    return newVal.call(this, ...args);
                }
            } else {
                C.prototype[k] = newVal
            }
        } else {
            C[k] = newVal;
        }
    }
} 
```
It just provides a "odooish" way of patching components (or classes):

```js

patch(SomeComponent, {
    setup() {
       this._super(); // 
       // can use hooks here!
       // ...
    },
    g() {
       console.log('in some other method');
       // here, this._super is available if necessary
    }
});
```
The `patch` method is not strictly necessary, because methods can always be patched by hand, but it is a very short helper which provides a nice syntax

**Comment by rauletepaz** [comment]
Thanks geg.

     It seems pretty good. But the setup method doesn´t work for me, are you sure that this method it's called by the component's constructor? I couldn't find it. In my example it is possible to use the _constructor method that it exists in the Message component in "mail/static/src/components/message/message.js", but there isn't in others components.

**Comment by ged-odoo** [comment]
@rauletepaz yes, you are right, it is not there yet in Owl. I have a small branch doing that, but the PR is not ready yet. It is coming soon, really, I promise (except that the final name may be `setup` or `init`, not sure yet!)

**Comment by LuisMalave2001** [comment]
I will close this issue because it was already fixed in https://github.com/odoo/owl/commit/19a47a7001a90ca6fd6a1a668b7107e5af4c74bf

Thanks for paying attention to this request.

Kind regards
