### ISSUE TITLE
Props validation of strings

### ISSUE THREAD

**Issue by VincentSchippefilt** [odoo/owl#795]
In o-spreadsheet, when integrating with delayed translation functions (aka `_lt`) the result of this function is an object that has a property `toString`. If this object is bound to a prop that has validation and is defined as string, the validation will fail.
I think we should change the validation of strings so it matches strings but also objects that have the `toString` property.

**Comment by ged-odoo** [comment]
after discussion, it seems like the correct solution is to subclass String. The `web` addon uses this class:
```
class LazyTranslatedString extends String {
    valueOf() {
        const str = super.valueOf();
        return _t(str);
    }
    toString() {
        return this.valueOf();
    }
}```

With this, the props validation should work, and it seems more correcter. So, I'll close this issue.
