### ISSUE TITLE
State management: only render subcomponents impacted by state change

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#815]
The motivation for this issue is that Owl render a component and all its subcomponent each time an observed piece of state changes, and it would be interesting to have a better strategy.

Example 1: if a root component has a counter and a large number of child component, incrementing that counter will cause a complete rerender of the application, instead of just updating the counter value on the screen

Example 2: if a component has a useState with `{a:1, b: 2}` and the value `b` is not used in the render, modifying the value `b` will cause a rerender, even though it is useless

For now, these performance issues can be solved with various strategies:
- transform (artificially) some part of a component into a subcomponent, so their update does not affect the rest (so, for example, the counter in example 1)
- implement `shouldUpdate` in a bunch of subcomponents (every other subcomponents in example 1)
- do not observe some part of the state (or remove it if it is useless) as in example 2

Other frameworks have interesting strategies:
- SolidJS is really finegrained, so it will only update what is necessary. However, data model leaks in component management, with the need for a way to batch some operations
- VueJS has the concept of observer, that can keep track of what component is impacted by a rendering. Maybe we should do that?

It would be interesting to think about what we can do to solve/improve the performance situation.

**Comment by ged-odoo** [comment]
@seb-odoo

**Comment by seb-odoo** [comment]
@ged-odoo do you plan to close all such issues at once when Owl 2 is released, or should they be progressively closed as they are done in the next branch?

**Comment by ged-odoo** [comment]
@seb-odoo once owl 2 is released I guess. Closing them now would be lying I think.

**Comment by ged-odoo** [comment]
fixed in owl 2
