### ISSUE TITLE
Question: Vdom/QWeb

### ISSUE THREAD

**Issue by renlite** [odoo/owl#838]
Is it possible to define the ui/vnodes with h() functions without QWeb/XMLTemplates?

**Comment by ged-odoo** [comment]
Very good question. Sadly, the answer is no, for now. Owl is very new, and we had to learn a lot on how to organize the Owl internal code.  But this is definitely a useful feature, which is actually related to https://github.com/odoo/owl/issues/778.

Hopefully, this (or something similar) will be possible in Owl 2.0 (which is not really planned yet, but I hope that I can work on it at the end of the year, so maybe end of 2021, early 2022)
