### ISSUE TITLE
keep exceptions uncaught in dev mode (suggestion)

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#840]
Hello,

When we have an issue in business code, we will have an exception that looks something like the following:
```
Uncaught (in promise) TypeError: formatFunction is not a function
    at message.js:312
    at Array.map (<anonymous>)
    at Message.get trackingValues [as trackingValues] (message.js:301)
    at QWeb.eval (eval at _compile (owl.js:1695), <anonymous>:450:18)
    at QWeb.fn (owl.js:1567)
    at QWeb.render (owl.js:1617)
    at Object.__owl__.renderFn (owl.js:4595)
    at Message.__render (owl.js:4391)
    at Message.__prepareAndRender (owl.js:4379)
```

However, due to `__render` catching the exception, it is not possible to use the browser debugger feature "pause on exceptions". The feature "pause on _caught_ exceptions" is out of the question because it will pause on many random crap from other libs.

My suggestion is that if OWL is in dev mode, the exception should simply not be caught.

**Comment by seb-odoo** [comment]
As per discussion, the error management is a core feature of the framework, so it's not good to change its behavior in dev mode.

As a decent alternative it is possible to ignore/blackbox in browser dev tools the other libs that are doing stupid caught exceptions so that "pause on caught exception" actually works without too much noise.

I'll take this as a solution for now, feel free to close unless you think something else can still be done in OWL to further improve this case.

**Comment by ged-odoo** [comment]
ok. thanks anyway for the feedback :)
