### ISSUE TITLE
t-transition: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#842]
Hello,

Here is an error that we received from OWL when using `t-transition`.
I suspect it happens if the element that is the target of the transition is removed from the DOM before the transition completes.

I can look into reproducing on the playground if needed, but I don't have any more info than what is below.

```
owl.js:1157 Uncaught TypeError: Cannot read property 'removeChild' of null
    at Object.removeChild (owl.js:1157)
    at rmCb (owl.js:879)
    at HTMLDivElement.finalize (owl.js:2603)
removeChild @ owl.js:1157
rmCb @ owl.js:879
finalize @ owl.js:2603
```

**Comment by ged-odoo** [comment]
"fixed" in owl 2, by removing support for transitions
