### ISSUE TITLE
Suggestion: non prop attributes

### ISSUE THREAD

**Issue by mcm-odoo** [odoo/owl#843]
Would be nice to have something to define where `class` and `style` attributes are bound in a component.

for the example, the root element of a dialog is a portal so writing `<Dialog class="my-dialog" t-att-class="...">...`
will bound classes on the portal element. We need to use a props to define where it should bind.

e.g.
```xml
<Portal target="'body'">
  <div class="o_dialog" t-att-class="props.contentClass">
    ...
  </div>
</Portal>
...
<Dialog contentClass="'...'">...</Dialog>
```

Why not having a directive or something similar to Vue3's component attributes (https://v3.vuejs.org/guide/component-attrs.html)
or a mix of the two?

```xml
<Portal target="'body'">
  <div class="o_dialog" t-attrs="class">  <!-- bind the class attribute with a directive -->
    ...
  </div>
</Portal>
```

> We'll also need something like this for multi-rooted components in owl 2.0

**Comment by ged-odoo** [comment]
this one is actually even more interesting once we implement multiple roots components, because in that case, there is no canonical way to decide where the class attribute should be applied

**Comment by ged-odoo** [comment]
done in owl 2 (class and style are now normal props)
