### ISSUE TITLE
minor suggestion: use build commit instead of "master" in doc link of "Owl is running in 'dev' mode

### ISSUE THREAD

**Issue by seb-odoo** [odoo/owl#850]
I'm talking about the following message:

`Owl is running in 'dev' mode.  This is not suitable for production use. See https://github.com/odoo/owl/blob/master/doc/reference/config.md#mode for more information.`

If I'm using an older version of OWL, I would be expecting to find the documentation for the version I am using, instead of a link in master that may or may not be relevant at the time.

Edit: I'm suggesting build commit, but it could also maybe be release tag, or a specific versioned branch, depending on how versioning will be handled when OWL v2 comes out.

**Comment by sambeauvois** [comment]
Hello,
I'm using odoo 15 on premises, 
I'm getting a 404 on the https://github.com/odoo/owl/blob/master/doc/reference/config.md#mode

**Comment by ged-odoo** [comment]
@sambeauvois yeah, the doc was updated in owl 2, and the configuration page was moved to https://github.com/odoo/owl/blob/master/doc/reference/app.md#configuration
