### ISSUE TITLE
t-foreach: only renders the last entry when a list of dicts is injected from JS

### ISSUE THREAD

**Issue by EwetoyeIbrahim** [odoo/owl#851]
**Problem**: When trying to pass a variable value from JS to XML, only the last entry got rendered with a `t-foreach` directive.

**Current Result**: Only the last item gets to the DOM
```
<div class="p-3 bg-light">
  <h5>ertyujbhjkl</h5>
  <p>buy cake</p>
  <p>fjkjjjjj</p>
</div>
```
**Expected**:  Each of the items should get presented
```
<div class="p-3 bg-light">
  <h5>fsfgshsj</h5>
  <p>buy milk</p>
  <p>yuu</p>
</div>
<div class="p-3 bg-light">
  <h5>ertyujbhjkl</h5>
  <p>buy cake</p>
  <p>fjkjjjjj</p>
</div>
```

**Codes**:

JS
```
function app() {
    class TestCall extends owl.Component {
        constructor() {
            super(...arguments);
            this.items = [
                {
                    id: 3,
                    title: "fsfgshsj",
                    date: "buy milk",
                    about: "yuu",
                },
                {
                    id:4,
                    title: "ertyujbhjkl",
                    date: "buy cake",
                    about: "fjkjjjjj",
                },
            ];
        }
    }

    class App extends owl.Component { }
    App.components = { TestCall };


    //------------------------------------------------------------------------------
    // Application Startup
    //------------------------------------------------------------------------------

    owl.mount(App, { target: document.body });

}

/**
 * Initialization code
 * This code load templates, and make sure everything is properly connected.
 */
async function start() {
    let templates;
    try {
        templates = await owl.utils.loadFile('app.xml');
        console.log('found')
    } catch (e) {
        console.error(`This app requires a static server.  If you have python installed, try 'python app.py'`);
        return;
    }
    const env = { qweb: new owl.QWeb({ templates }) };
    owl.Component.env = env;
    await owl.utils.whenReady();
    app();
}

start();
```

Template:
```
<templates>
    
    <t t-name="TestCall" t-foreach="items" t-as="item">
        <div class="p-3 bg-light" t-key="item.id">
            <h5 t-esc="item.title"></h5>
            <p t-esc="item.date"></p>
            <p t-raw="item.about"></p>
        </div>
    </t>

    <div t-name="App" class="app">
        <TestCall />
    </div>
</templates>
```

**Comment by ged-odoo** [comment]
Hello @EwetoyeIbrahim . Your issue is actually not with `t-foreach` but with components. Owl (for now) does not support a component with multiple roots, and this is what you are doing.  If you simply change `<t t-name="TestCall" ...` into `<div t-name="TestCall"... `, this should work.  Or you can have a `t-call`. The only problem is if a component has multiple roots. This is just not supported by the vdom implementation (but in the future, I have a prototype for owl 2.0 where this will work)

**Comment by EwetoyeIbrahim** [comment]
> If you simply change `<t t-name="TestCall" ...` into `<div t-name="TestCall"... `, this should work

@ged-odoo, changing into <div t-name="TestCall"... still exihibits the same issue.

```
<div t-name="TestCall" t-foreach="items" t-as="item">
        <div class="p-3 bg-light" t-key="item.id">
            <h5 t-esc="item.title"></h5>
            <p t-esc="item.date"></p>
            <p t-raw="item.about"></p>
        </div>
</div>
```
If I am right, `t-call` is for injecting another XML file, maybe with arguments or not, but my aim is to pass a list of dicts (objects) from JS side into XML.

Thanks for your response.

**Comment by ged-odoo** [comment]
hmm, I was too fast. Indeed, the change from `t` to `div` is still applied after `t-foreach`, so obviously, you are right and it does not work. Try this instead:

```xml
    <div t-name="TestCall">
        <div class="p-3 bg-light" t-foreach="items" t-as="item" t-key="item.id">
            <h5 t-esc="item.title"></h5>
            <p t-esc="item.date"></p>
            <p t-raw="item.about"></p>
        </div>
    </div>
```

This moves the `t-foreach` below the `div`

**Comment by EwetoyeIbrahim** [comment]
Thanks for the clarification.

Now, I guess I know what you meant by "multiple roots" is what I would have understood by "Nested tags". If I am not missing something.

Thank you, let me keep learning from leaders like @ged-odoo.
