### ISSUE TITLE
vdom crash when `updateChildren`

### ISSUE THREAD

**Issue by caburj** [odoo/owl#854]
In the following line

https://github.com/odoo/owl/blob/7dfa90133207bb7f85c9bbbb7813301e95a61911/src/vdom/vdom.ts#L341

`elmToMove` is assumed to be a `VNode` because it's extracted from a variable with type `VNode[]`. However, I believe there is no guarantee that the array when indexed will always return a `VNode`. There is a chance that the result is `undefined`. And if you look in the following line 

https://github.com/odoo/owl/blob/7dfa90133207bb7f85c9bbbb7813301e95a61911/src/vdom/vdom.ts#L349

`undefined` is explicitly set to an index in the array. The typescript check is ignored because of the use of `as any`.

I have a situation in pos where I'm loading 15k products. But all the time, only the top 1k is rendered. In this case, I encountered a situation where `elmToMove` is actually `undefined` which results to a crash in the UI. Here is a short clip to demo the problem.

https://drive.google.com/file/d/1irQoXDW7jSk9z4l-4vu2eyuVF9B_mCZz/view

You will see the debugger paused on the breakpoint at `1:15`.

For added context, here is an excerpt of the template that crash:

```html
            <div class="product-list-container">
              <t t-set="productsToDisplay" t-value="getProductsToDisplay()" />
              <div t-if="productsToDisplay.length != 0" class="product-list">
                <t t-foreach="productsToDisplay" t-as="product" t-key="product.id">
                  <!-- ProductItem -->
                  <article class="product" tabindex="0" t-on-keypress="onSpaceClickProduct(product)"
                    t-on-click="trigger('click-product', product)" t-att-data-product-id="product.id"
                    t-attf-aria-labelledby="article_product_{{product.id}}">
                    <div class="product-img">
                      <img t-att-src="getProductImageURL(product)" t-att-alt="product.display_name" />
                      <span class="price-tag">
                        <t t-esc="getProductDisplayPrice(product)" />
                      </span>
                    </div>
                    <div class="product-name" t-attf-id="article_product_{{product.id}}">
                      <t t-esc="product.display_name" />
                    </div>
                  </article>
                </t>
              </div>
```

**Comment by caburj** [comment]
I am able to reproduce using this toy example:
https://github.com/caburj/my-owl-playground/tree/main/updateChildren-crash

**Comment by caburj** [comment]
This can happen because of duplicated `t-key`. In the case of the example template above, whenever `productsToDisplay` is computed, not all of the time its items are unique. It's possible that an item is referenced in multiple indexes. This is a bug in pos. However, crashing the UI without explanation is a bad developer experience.

We can replicate the error in this toy example: https://github.com/caburj/my-owl-playground/tree/main/updateChildren-crash

**Comment by ged-odoo** [comment]
closed in owl 2. there is now a warning in dev mode when we have duplicate key
