### ISSUE TITLE
Suggestion: slots props

### ISSUE THREAD

**Issue by mcm-odoo** [odoo/owl#856]
Could be **nice to have** component's slots that gives "props" to parent's context.

```xml
<t t-name="CompWithSlotProps">
  <div>
    <t t-slot="slot" t-slot-props="{ value: 'Hello World!' }" />
    <!-- t-slot-props combined with t-slot would bind data to the slot -->
  </div>
</t>
...
<CompWithSlotProps>
  <t t-set-slot="slot" t-slot-props="slotProps">
  <!-- t-slot-props combined with t-set-slot would give data bound from the slot -->
    <!-- slotProps is accessible only in the slot's scope -->
    <t t-esc="slotProps.value" />
  </t>
  <t t-esc="slotProps" />
  <!-- slotProps is undefined as it is not in the current scope -->
</CompWithSlotProps>
```

Vue.js has this feature <https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots>
It could be interesting to have a such feature. It would improve the definition of HOC.

e.g.
At the moment we have a `WithSearch` component that creates a `SearchModel` and sets it in the env.
Its template looks like:
```xml
<t t-name="WithSearch">
  <t t-component="component" t-props="props" /> 
</t>
...
<WithSearch component="OtherComponent" props="componentProps" />
```
The problem with setting in env is that if we change a value then components won't be notified.
It could with `t-slot-props` if the "props" is in an `useState` in the HOC.

```xml
<t t-name="WithSearch">
  <t t-slot="default" t-slot-props="searchModel" />
</t>
...
<WithSearch>
  <t t-set-slot="default" t-slot-props="searchModel">
    <OtherComponent t-props="componentProps" searchModel="searchModel" />
  </t>
</WithSearch>
```
_(after 5 min of thinking about something else I reminded that we can also give the state in current design so it's not a good case :) )_

**Comment by ged-odoo** [comment]
it's done in owl 2
