### ISSUE TITLE
Dynamic routes only work in a simple and specific case

### ISSUE THREAD

**Issue by smottet** [odoo/owl#858]
When we use `navigate` with `to` and `params` set on the Destination object (and `path` not set) we expect the path associated to the named route to be parsed and transformed with the value of the params.

If we have the following route in our router:
```javascript
{name: 'MY_ROUTE', path: '/my/path#param1={{param1}}&param2={{param2}}', component: MyComponent}
```

And we call 
```javascript
router.navigate({to:'MY_ROUTE', params: {param1: 10, param2: 20}})
```

We expect as resulting path `/my/path#param1=10&param2=20` but instead we get `/my/10`. `MyComponent` should be rendered and params value accessible from it but this is not the case.

Currently dynamic paths seem to only work for paths following this format: `/my/simple/path/{{param1}}/{{param2}}/...`

https://github.com/odoo/owl/blob/7dfa90133207bb7f85c9bbbb7813301e95a61911/src/router/router.ts#L172-L186

![Screenshot from 2021-05-17 15-28-23](https://user-images.githubusercontent.com/49784121/118496628-974c5580-b724-11eb-99c2-b9d9dd264233.png)

**Comment by ged-odoo** [comment]
good issue. it should be reasonably easy to solve

**Comment by JKE-be** [comment]
Hello Gery, any ETA since 'reasonably easy' to know if we need to find an hack (use another storage than url) or not ? 
We hope to merge it for next freeze.

ty for follow up

**Comment by ged-odoo** [comment]
@JKE-be no promise, but I assume that the fix can be done quickly. I'll try to ask someone to have a look tomorrow

**Comment by rdeodoo** [comment]
This is more than `quickly`, this is blazing fast !

**Comment by JKE-be** [comment]
thankyou veryyyy mouchhhh

**Comment by ged-odoo** [comment]
fyi, the odoo update PR is: https://github.com/odoo/odoo/pull/71023/files 
Should be merged today

**Comment by smottet** [comment]
Nice! Thank you Géry and Sam!
