### ISSUE TITLE
Router can't be started with url containing query string and/or fragment

### ISSUE THREAD

**Issue by smottet** [odoo/owl#863]
If you try to start the router with an url containing query string and/or fragment you get the following error:

![Screenshot from 2021-05-25 09-17-39](https://user-images.githubusercontent.com/49784121/119455702-24e9ff80-bd3a-11eb-99f4-58207e66773e.png)

It looks like that adding `+ window.location.search + window.location.hash` at line 187 solves the problem.

https://github.com/odoo/owl/blob/e8387810e63e542aea6852205646691c1fd9ea60/src/router/router.ts#L186-L189

**Comment by smottet** [comment]
@sdegueldre @ged-odoo @JKE-be an other small problem with the router.

**Comment by JKE-be** [comment]
>  and I don't think that this is a use case we want to support

not sure to understand the problem...

It is the same than /web?debug=1#menu_id=6 no ?

**Comment by sdegueldre** [comment]
Yes. We do not use this router in Odoo, we have a custom router. The owl router is intended for standalone applications.

**Comment by sdegueldre** [comment]
Not really. First of all, we use a custom router in Odoo, not the owl router.

Second, the router only touches the hash part of the URL, if we want to touch the path, we don't go through the router. In this case, @smottet wanted to use the router to manage both the url path and the url hash, but currently, the router treats the hash as a string, which means that it has no understanding of "hash params", so if the order of the hash params changes or there are extra hash params, the route won't match.

**Comment by JKE-be** [comment]
yes ok, mean that we should use step as an hash and not as an element from path.
But at the end, since we need to keep the logo, the hash will be not the right/final solution.

Ty for feedback...
