### ISSUE TITLE
odoo owl searchbar input  inherit problem

### ISSUE THREAD

**Issue by farshidpakro** [odoo/owl#870]
odoo.define('web_customize.basic_fields', function (require) { "use strict";

const SearchBar = require('web.SearchBar');

// const Registries = require('web.Registry');

const mySearchBar = SearchBar =>

    class extends SearchBar {

        constructor() {

            super(...arguments);

        }

        _onSearchInput(ev) {

            alert('button clicked');

        }

    };

SearchBar.Component.extend(SearchBar, mySearchBar);

return SearchBar;
});
// cant inherit in this way

**Comment by farshidpakro** [comment]
hi . i will so happy if you help to inherit search bar input or class inherit

**Comment by ged-odoo** [comment]
@farshidpakro Components can be extended/modified with the `patch` method.  We kind of experimented various approachs, including the patchmixin you are probably talking about, but at the end, we decided that the best approach is to define a simple `patch` method, which is similar to the old `widget.include` feature. Here is how you could modify an existing component:

```js
odoo.define('web_customize.basic_fields', function (require) { "use strict";

const SearchBar = require('web.SearchBar');
const utils = require('web.utils');
const patch = utils.patch;

patch(SearchBar, 'web_customize.mypatch', {
    _onSearchInput(ev) {
        alert('button clicked');
        this._super(ev); // just like include, you can access the parent method with _super
    }
});
```

Note that if you just want to create a sub component, standard inheritance is fine:

```js
odoo.define('web_customize.basic_fields', function (require) { "use strict";

const SearchBar = require('web.SearchBar');

return class MySearchBar extends SearchBar {
    _onSearchInput(ev) {
        alert('button clicked');
        super._onSearchInput(ev); // here, the `super` keyword from javascript has to be used
    }
}
});
```

**Comment by arabkhemar** [comment]
@ged-odoo the 2 methods don't work for me on v15 ! Any idea ?

**Comment by arabkhemar** [comment]
> @ged-odoo the 2 methods don't work for me on v15 ! Any idea ?

Got it! Missed the `.prototype` thanks to docs :)
