### ISSUE TITLE
Owl Tutorial setting issue

### ISSUE THREAD

**Issue by guidev224** [odoo/owl#879]
Hello,

I am trying to follow the owl tutorial for beginner and have copied the content of this file [OWL JS FILE](https://github.com/odoo/owl/releases/download/v1.3.2/owl.cjs.js)

But I am getting this error `Uncaught ReferenceError: exports is not defined.` at this line `Object.defineProperty(exports, '__esModule', { value: true });
`
I have even installed node js on my machine but still getting the error

I have followed thoroughly the tutorial guide

App Structure
```
todoapp/
    index.html
    app.css
    app.js
    owl.js

```

index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>OWL Todo App</title>
    <link rel="stylesheet" href="app.css" />
    <script src="owl.js"></script>
    <script src="app.js"></script>
  </head>
  <body></body>
</html>
```

app.js
```
(function () {
	console.log("hello owl", owl.__info__.version);
  })();
```

**Comment by ged-odoo** [comment]
you should take the iife version (same file name, but with iife). The cjs is for use in bundlers/other kind of tooling. Sorry, the js ecosystem is kind of a mess! We should add a note to clarify that in the tutorial.

**Comment by guidev224** [comment]
@ged-odoo thanks for your response. I'll give it try
