### ISSUE TITLE
[BUG?] Hyphens not supported in "t-set"

### ISSUE THREAD

**Issue by Arcasias** [odoo/owl#881]
## Scenario
```js
const { Component, mount, tags } = owl;

class App extends Component {
    static template = tags.xml`
        <div>
            <t t-set="some-value" t-value="1" />
            <t t-esc="some-value" />
        </div>
    `;
}

(async () => {
    await mount(App, { target: document.body });
})()
```
## Problem
The code above breaks because it uses the `scope.key` notation instead of `scope["key"]`. Hyphens are valid in standard JS object keys and I think it would make sense to support them in QWeb context keys as well.

**Comment by ged-odoo** [comment]
@Arcasias I was doing a commit to solve this issue, everything was going fine for the `t-set/t-value`. However, I encountered an interesting problem with the `t-esc`: `t-esc` allows an arbitrary expression, so it is actually valid to escape the `some - value` expression.

so, in short, adding the support for hyphens in  `t-set/t-value` looks mostly useless if we cannot get the value out anyway?

**Comment by Arcasias** [comment]
That... is pretty valid, I actually didn't think about that since I got the compilation error before it could even happen. I'll close this issue for now then.
