### ISSUE TITLE
t-set: do not interpret body content as vdomarray

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#895]
The current way of handling t-set as a VDomArray is smart, but can leak very easily. For example, in the following template:

```xml
<t t-set="name">Database</t>
<SortableColumnHeader name="name" code="'__name'" />
```
the sortablecolumnheader will receive a vdomarray in `props.name`. It is probably not so good to leak internal detail like that, and also, the question arises, is it really needed and can we get away with simply interpreting the content of the body as a string?

**Comment by ged-odoo** [comment]
not clear that it can/should be done. One reason for the current design is also that we initially used the `t-set` to define slots, which is no longer the case so maybe we have one less reason to keep the vdomarray. But another more serious question is what to do with this:

```xml
            <t t-set="_badge_text">
                <span class="o_badge_text" t-att-title="el.display_name"><span role="img" t-attf-aria-label="Tag color: #{colornames[color]}"/><t t-esc="el.display_name"/></span>
            </t>
            <t t-if="hasDropdown">
                <a role="button" href="#" class="dropdown-toggle o-no-caret" data-toggle="dropdown" aria-expanded="false">
                    <t t-raw="_badge_text"/>
                </a>
            </t>
            <t t-else="">
                <t t-raw="_badge_text"/>
            </t>
```
This means that the content of the `t-set` has to be rendered. So, we need to basically convert it to a sub template and render it with the current scope. Or we decide that it should not be rendered, and convert all these cases in a separate `t-call` statement instead.

**Comment by sdegueldre** [comment]
Handled properly in owl 2
