### ISSUE TITLE
Patching/Extend owl component: JS/XML/...

### ISSUE THREAD

**Issue by umar3ziz** [odoo/owl#899]
am trying to patch 'mail/static/src/components/message/message.js' file and need to extend the behavior of `get trackingValues()` but super return `undefine` and the log for `this` inside return nothing not like the the `_constructor()` i can see everything from `_constructor() ` function so idk if this is issue or i can't do it right to override a property (get -) function.

`

    odoo.define('my_module/static/src/components/message/message.js', function (require) {
    'use strict';
    
    const components = {
        Message: require('mail/static/src/components/message/message.js'),
    };
    
    const { patch } = require('web.utils');
    
    patch(components.Message, 'my_module/static/src/components/message/message.js', {
        /**
         * @override
         */
        _constructor() {
            this._super(...arguments);
            console.log("_constructor THIS", this) // this works fine
            console.log("_constructor trackingValues", this.trackingValues) //  i can read the trackingValues from here normally
        },
    
        get trackingValues() {
            const value = super.trackingValues;
            console.log("trackingValues value", value) // this print undefin
            console.log("trackingValues THIS", this) // this print {}
    
            return value
        }
    
    });
    
    });

`

**Comment by ged-odoo** [comment]
in what version are you working? 14.0?

**Comment by umar3ziz** [comment]
@ged-odoo yes

**Comment by ged-odoo** [comment]
@mcm-odoo maybe you could check this?

**Comment by sdegueldre** [comment]
This has been fixed in Odoo
