### ISSUE TITLE
Is there any problem with writing this way?

### ISSUE THREAD

**Issue by yao-big** [odoo/owl#901]
odoo.define('web.inherit.Pager', function (require) {
    'use strict';
    const components = {
        webPager: require('web.Pager')
    };
    const {patch} = require('web.utils');
    patch(components.webPager, 'web.inherit.Pager', {
        constructor() {
            this._super(...arguments)
            console.log('constructor')
        },
    });

});

### Unable to solve this error

**I want to add a parameter to the constructor. It can't be added or printed**

![image](https://user-images.githubusercontent.com/30170943/127119534-bc91e775-dd25-4489-88c1-7a552ca87403.png)

**Comment by ged-odoo** [comment]
yes, the javascript language does not handle the constructor method like other methods in a class, so it is not possible to  override the constructor. Instead, in owl, each component call the `setup` method, so it can be overridden. So, in your case, try overriding `setup` instead

**Comment by Leuan12** [comment]
ok
