### ISSUE TITLE
[t-on] additional arguments are not always refreshed

### ISSUE THREAD

**Issue by brboi** [odoo/owl#902]
Consider a template where a node has a `t-on` directive and its value is a callback taking some additional arguments from the scope:
```xml
<... t-on-any-event="callback(arg1, arg2)"/>
```

On a subsequent rendering, this node could potentially be updated instead of being entirely renewed.
In that case, the additional arguments are not recomputed with the updated scope, leading to inconsistent behavior.

For now, a workaround is to use a proper `[t-key]` attribute, in order to force a renewal of the node.

**Comment by ged-odoo** [comment]
fixed in owl 2
