### ISSUE TITLE
Attempting to patch a fiber that hasn't been rendered and more weirdness.

### ISSUE THREAD

**Issue by sdegueldre** [odoo/owl#904]
see odoo-dev:master-owl-fiber-scheduling-canceling-bug-sad

From the discuss app, click discuss in the main menu.

crash seems to indicate that we're attempting to patch a component using a non-rendered fiber.

There is a second error where we appear to attempt to patch a component with no vnode with a (rendered this time) fiber.

Edit: more notes

a description of the sequence that I think causes the issue, consider we have components A and B where A is B's parent

A __renders (as part of fiber 0), creates a fiber (fiber 1) to render B
A __renders again, creates a new fiber (fiber 2) to render B that cancels fiber 1
The canceling of fiber 1 decreased fiber 0's counter to 0, the next flush tries to complete fiber 0 but it contains the canceled fiber 1 in its descendants. Crash. What's the expected outcome when completing a fiber with canceled descendants?

**Comment by aab-odoo** [comment]
@sdegueldre There's something I don't understand in your description:

> The canceling of fiber 1 decreased fiber 0's counter to 0,

when A creates a fiber for B, it increases its counter, so as it creates a fiber twice, it should increment its counter twice (whereas cancelling the first fiber decrements the counter once). So it should not be 0 until the final B's fiber is ready...

**Comment by sdegueldre** [comment]
@aab-odoo My memory of the exact mechanics is a little fuzzy since it's been a while since I looked into it, so take what follows with a grain of salt, but from what I remember, it *isn't* 0 until the final fiber for B is ready, the problem is that when this becomes the case, we patch fiber 0 and its children, one of which is canceled and has no vnode, hence cannot be patched.
