### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by thomaspaulb** [odoo/owl#912]
In light of https://github.com/odoo/owl/issues/12, what does this mean for the browser versions that are / aren't supported?

https://caniuse.com/?search=es6

Is for example Chrome 44 supported? It could be found on old Android phones, making it perhaps undesired to integrate OWL with the website frontend.

**Comment by sdegueldre** [comment]
We don't want to support es5 because the generated code has a lot of extra overhead in modern browsers. If you need better browser support you can simply use owl as a node module and configure your bundler exactly how you want it including any necessary down-compilation.
