### ISSUE TITLE
Override service!

### ISSUE THREAD

**Issue by shurshilov** [odoo/owl#954]
99% of the ode modules are modules of third-party developers. which do override in each module. So why the fuck is it so hard with owl! Give me the code that will allow me to earn my excel report module on version 15, I sat for 2 hours and except for programming solutions in a straight line with 0, I found nothing. Is it really impossible to create a redefinition tutorial. Look at the forums this is the most common problem. I wrote a simple article for version 14 and have already more than 500 views, although the rest of my articles are 100-200. Your owl is very much slowing down development on odoo apps. The Bacbone system is modular and this is its main advantage. OWL IS NOT MODULAR. THIS!

**Comment by shurshilov** [comment]
/** @odoo-module **/

import { actionService } from "@web/webclient/actions/action_service";
import { registry } from "@web/core/registry";
import { patch } from 'web.utils';
import { useService } from "@web/core/utils/hooks";

registry.category("ir.actions.report handlers").add("custom_xlsx", async (action,options, env) => {
    console.log(action)
    console.log(options)
    console.log(env)
    console.log(this)
    console.log(actionService.start(env))
        if (action.report_type === 'excel') {
            // this.actionService = useService("action");
            return action._triggerDownload(action, options, 'excel');
        }
        //return this._super.apply(this, arguments);
});

How I can call private method???????????

/** @odoo-module **/

import { actionService } from "@web/webclient/actions/action_service";
import { registry } from "@web/core/registry";
import { patch } from 'web.utils';
import { useService } from "@web/core/utils/hooks";

registry.category("ir.actions.report handlers").add("custom_xlsx", async (action,options, env) => {
    console.log(action)
    console.log(options)
    console.log(env)
    console.log(this)
    console.log(actionService.start(env))
        if (action.report_type === 'excel') {
            // this.actionService = useService("action");
            return action._triggerDownload(action, options, 'excel');
        }
        //return this._super.apply(this, arguments);
});

**Comment by ged-odoo** [comment]
@shurshilov Sorry to hear about your frustration. Services are indeed harder to customize now, and I am responsible for that change.

However, that does not mean we do not try to improve and make our code more extensible. We simply want to make it extensible in a safer way.  In this case, a possible solution would be that the handler could receive some additional object with access to some useful internal methods, such as triggerDownload. We actually had some discussion on the best way to expose internals of the action service (the goal is to define all action handlers outside of the action service).  

I understand that it will probably not satisfy you, but this is a tradeoff: in return, we gain a more stable ecosystem, which also has some value. Services (and in particular action service) are really technical, and it is risky to modify it. Also, it forces us to make sure the action service is powerful enough for everyone's needs. In this case, it seems like there is a need that we should fulfill. Would the solution above completely solve your issue? Or is there some other aspect of the action service that you really need to access?

In the meantime, this may be a hack, but I think that there is a workaround so you can make it work: you can simply copy the code of the `_triggerDownload` and of the `_getReportUrl` methods in your js file. This is about 40 lines of code, and should do the trick.

**Comment by shurshilov** [comment]
I am a supporter of the odoo, and I see how you are improving the frontend, this is really true. I see that the mail module has been rewritten more beautifully, less code, and many unnecessary lines of code have been removed. The code is really better and more thoughtful, it pleases. Of course reactivity is a brilliant invention that we are currently using)Thanks)

But the backbone.js was big, complex, slow, but **modular.** Please keep modularity as you rewrite) this is very important for 3rd-party developers)

Yes, as a result, yesterday I copied these two functions. But we understand that this is a bad practice in support (if something changes there in the future, I will have to change as well) and plus a lot of extra code)

In any case, thank you, I saw how in version 14 files with owl  beautifully upload files and  how easily I used it in my modules, and how beautifully the attachments were rewritten, my code began to work both in chat and in chatter and discuss and compose everywhere - it's brilliant.
Don't forget modularity please!
Thanks!

**Comment by shurshilov** [comment]
I just looked and it turns out you completely rewrote mail in version 14, I understood it and it was cool. But why did you rewrite it again in version 15?I was talking about how cool it works in the message above, but now it works badly!!!Didn 't you have another job how to rewrite 3 times what you rewritten from 13 to 14 and now from scratch from 14 to 15 !This is the worst project management I've seen. I will leave odoo for other frameworks and advise this to the entire community that I know. It totally sucks!!!

**Comment by kebeclibre** [comment]
Modularity is at the core of Odoo . We are refactoring and converting to owl to have a more robust way to extend the behavior of our elements, and ultimately to improve the programming experience of partners in Odoo. Suren we must have forgotten stuff, or decided not to reimplement them. The goal is to start almost anew and develop what is needed in the future, not the other way around.

Now your points are not directed to Owl, which must be seens as a low-level templating framework. From this point of view, this is not the right place for this issue.

Everybody is always welcome to make honest points about the architecture or code or features -- given that there must be a reason for us to do what we do, especially if it is a change -- , but then again those should be constructive, that is: argumented and targetted to the right developpement team.

**Comment by shurshilov** [comment]
I agree the transition to the new js platform is a very difficult task, thank you for success! Don't forget about odoo apps developers when designing!
